### ISSUE TITLE
Remove dependency on redux-simple-router?

### ISSUE THREAD

**Issue by mjrussell** [mjrussell/redux-auth-wrapper#1]
Currently there is a hard dependency on `redux-simple-router` due to https://github.com/mjrussell/redux-auth-wrapper/blob/master/src/index.js#L2

The replace (or push) action creator could easily be passed in as an argument. Is it better to add this option or make it convenient since simple router is the rackt approved method?

**Comment by mjrussell** [comment]
I think this library should be agnostic to the routing library used, making it work with both.

Going to provide an option for specifying the action creator to call and default to the history prop passed down

**Comment by jbach** [comment]
Until you’ve decided, you should replace redux-simple-router with react-router-redux, the project has been renamed/deprecated.

**Comment by mjrussell** [comment]
@jbach thanks will do. I've decided to take out the hard dependency anyway but will allow users to specify their own route actions to dispatch if they want. I'll try to do this and #8 today and get a new release out.
