### ISSUE TITLE
Include example/suggestions for local storage

### ISSUE THREAD

**Issue by mjrussell** [mjrussell/redux-auth-wrapper#10]
Currently there isn't a great way to use local storage.

The best solution right now is to have a call similar to "what user am I?" maybe like a `/api/users/me` or similar. This will set the userAuthData in the store if successful and be dispatched on application load. On a 401, you clear this data out of the store. 

This way your app doesn't even know about a cookie in localstorage, it just knows if there is a user or not. When you login successfully, you can dispatch the `getUser` using something like `redux-thunk`.

Should document this better or provide an alternative way.

One such alternative could be to provide a "isLoggingIn" selector which will display a component of the user's choice while this value is true instead of performing a redirect or showing the authed component

**Comment by mjrussell** [comment]
@mattkrick couple of thoughts there on local storage ^

**Comment by mattkrick** [comment]
You'll also need an `authError` state, because if both `isAuth` and `isAuthing` are false, you don't know whether the whole thing failed, or the whole thing hasn't started yet.

**Comment by mjrussell** [comment]
Yup good call, luckily this is a common pattern for redux actions and should be familiar with most people i.e. `LOGIN_SUBMITTED/FAILED/SUCCESS`

**Comment by eMerzh** [comment]
good idea, and if you got a logout exemple i'll be interested as well :)

**Comment by mjrussell** [comment]
See #35 for an ability to display a component while asynchronously performing the login request

**Comment by johnwiseheart** [comment]
My suggestion for this is using local storage in the action for LOGIN_SUCCESS/LOGOUT_SUCCESS as well as the initialState for the auth reducer:

In LOGIN_SUCCESS, you do something along the lines of:
`localStorage.setItem('jwt_token', response.token)`

Then in LOGOUT_SUCCESS, you clear the item:
`localStorage.removeItem('jwt_token')`

and finally in the initialState for your auth reducer:
```
const auth = (state = {
    isAuthenticated: localStorage.getItem('jwt_token') ? true : false
}, action) => {
...
```

This way, you can persist login on refresh. Thoughts?

**Comment by mjrussell** [comment]
@johnwiseheart yup I think that should work pretty well. You could also go one step further and use a setTimeout or kick off a saga to clear the token locally and clear the auth reducer if the token or cookie has an expiration date. Seems to me that the necessary features for this are probably all set, just want an example since its a common use case
