### ISSUE TITLE
Passing params to auth wrapper

### ISSUE THREAD

**Issue by sahil6111** [mjrussell/redux-auth-wrapper#109]
I want to pass ROLE as dynamic parameter to the auth wrapper so that it can be used in the predicate and same function can be used for all roles.

For e.g
`const ManageLink = VisibleOnlyToRole((roleName) => <Link to="/manage">Manage</Link>)`

Is this possible or any other way to do so?
Thanks
Sahil

**Comment by mjrussell** [comment]
Yes this is possible, define a function that returns an auth wrapper HOC:

```js
const VisibleOnlyToRole = (roleName) => UserAuthWrapper({
  authSelector: state => state.user,
  FailureComponent: null,
  wrapperDisplayName: 'VisibleOnlyToRole',
  predicate: user => user.role === roleName
})
```

Keep in mind that you don't want to keep recreating the React component in your render methods if you can help it. Ideally you apply the HOC outside the Component class definition and use it inside.

**Comment by sahil6111** [comment]
Thanks @mjrussell for the quick response :)
