### ISSUE TITLE
React Router v4 Documentation & Examples

### ISSUE THREAD

**Issue by mjrussell** [mjrussell/redux-auth-wrapper#112]
With the removal of `onEnter` and `onChange` in React Router v4 I think the auth-wrapper library makes even more sense. The docs talk about using the component lifecycle in your components for these features which is what redux-auth-wrapper already does!

Should be pretty easy just examples & docs, maybe a small breaking change in how the location/redirect is passed down

https://github.com/ReactTraining/react-router/blob/v4/README.md

**Comment by jedrichards** [comment]
Fyi everything seems to work well with RR4 already. It broke with their recent `beta7` release though, due to a minor change of the router `context` shape, but I notice you already have an issue for that https://github.com/mjrussell/redux-auth-wrapper/issues/127

**Comment by oyeanuj** [comment]
@jedrichards Have you tried it with SSR?

That's the one part where I think a different solution will be required given that `onEnter` has been removed.

**Comment by jedrichards** [comment]
@oyeanuj Ah no, I've only tried it out clientside ...

**Comment by roytz** [comment]
Sorry to be rude, but do you have an estimation to when will you sopprt RR4?

**Comment by mjrussell** [comment]
You aren't being rude...I've been a bad maintainer. Just been too busy with work and other things. Going to work on a bunch of these things today and hope to have something working for RR4 or an estimate by the end of the day

**Comment by roytz** [comment]
Thanks a lot @mjrussell !

**Comment by mjrussell** [comment]
wow...that was a lot more work than I anticipated trying to support both versions (mainly in test). But #133 is up! Needs documentation and examples but RR4 support should be very soon 😄

**Comment by roytz** [comment]
WOW! That was fast :)
Thanks
