### ISSUE TITLE
Stuck in a loop, trying to add roles to authentication

### ISSUE THREAD

**Issue by GeorgeKanchev** [mjrussell/redux-auth-wrapper#119]
A sample code is bellow, authentication works fine if we have 2 conditions, authenticated or not, but if I try nest a 'role check', it's stuck in an endless loop, because `UserIsNotAuthenticated ` is sending it to the page, then `UserIsNormal` fails and sends it back to login, and so forth.

Is there any way that I don't see to add checks for different roles, for example `Admin` should be able to go to `User` and `Admin`, but `User` should be sent to `Login` if he goes to `Admin`.

```
const UserIsAuthenticated = UserAuthWrapper({
  authSelector: state => state.user,
  authenticatingSelector: state => state.user.isLoading,
  failureRedirectPath: '/login',
  wrapperDisplayName: 'UserIsAuthenticated',
  predicate: user => user.token != null,
})

const UserIsNotAuthenticated = UserAuthWrapper({
  authSelector: state => state.user,
  authenticatingSelector: state => state.user.isLoading,
  wrapperDisplayName: 'UserIsNotAuthenticated',
  failureRedirectPath: (state, ownProps) => ownProps.location.query.redirect || '/',
  allowRedirectBack: false,
  predicate: user => user.token === null ,
})

const UserIsNormal = UserAuthWrapper({
  authSelector: state => state.user,
  authenticatingSelector: state => state.user.isLoading,
  wrapperDisplayName: 'UserIsNotAuthenticated',
  failureRedirectPath: (state, ownProps) => ownProps.location.query.redirect || '/',
  allowRedirectBack: false,
  predicate: user => user.role === 'normal' ,
})

const UserIsAdmin = UserAuthWrapper({
  authSelector: state => state.user,
  authenticatingSelector: state => state.user.isLoading,
  wrapperDisplayName: 'UserIsNotAuthenticated',
  failureRedirectPath: (state, ownProps) => ownProps.location.query.redirect || '/',
  allowRedirectBack: false,
  predicate: user => user.role === 'admin',
})
```
```
<Route name="Home" path="/" component={App}>
    <Route component={NotAuthenticated}>
        <Route name="Login" path="login" component={LoginWrapper} />
    </Route>
    <Route component={Authenticated}>
		<Route name="User" path="User" component={UserIsNormal(User)} />
		<Route name="Admin" path="Admin" component={UserIsAdmin(User)} />
    </Route>
</Route>
```

**Comment by tulbox** [comment]
I'm new to redux-auth-wrapper, but here's a quick guess: Should you not wrap the authentication checks as per https://github.com/mjrussell/redux-auth-wrapper#authorization--advanced-usage? E.g. 

`component={UserIsAuthenticated(UserIsAdmin(User))}`

Moreover, you might want to make your wrapperDisplayNames distinct to avoid any confusion when looking at the status of React in developer tools.

**Comment by mjrussell** [comment]
@GeorgeKanchev I think the issues is with your Normal wrapper. You dont need to send them to `/` do you (that doesn't appear to be a router in your route config)? 

Im not event sure if you need the Normal wrapper in this case, do you want to prevent users who are admins from going to `/User`? Also I think your failureRedirect path is probably wrong for Normal and Admin, the part for `ownProps.location.query.redirect` is only useful if you expect to be sent a redirect parameter which is usually only true for the `/login` route. Otherwise this can just be the path that users should go to when they dont meet the predicate check.

**Comment by mjrussell** [comment]
Closing since I haven't heard back, feel free to re-open if you are still having problems
