### ISSUE TITLE
How to trigger token check especially after page refresh (where state.auth.isAuthenticated no longer exists).

### ISSUE THREAD

**Issue by tulbox** [mjrussell/redux-auth-wrapper#120]
New to redux-auth-wrapper so I can't seem to quickly determine the best way to take care of the two following issues:

1. Avoid needing to re-log in after a page refresh (state is reset so isAuthenticated is no longer true even if there's a valid token).
2. I want to invalidate a token based on JWT expiry date. Where would this logic go? To say nothing of dealing with refresh tokens. As I'm writing this, likely something via the auth wrapper predicate, but in case I'm missing something obvious, still going to post here (look up token in cookie/localStorage, decode, grab the UTC date, and compare to see if still valid).

**Comment by tulbox** [comment]
Anybody care to point out if this is not the recommended way? It appears to work fine, but surprised it's not in any of the examples (as I'm sure I'm not the only one).

`predicate: (auth) => auth.isAuthenticated ? true : isAuthenticated()`

...where isAuthenticated is just a call to one of my authentication utility classes (checks if token is present and is still valid).

**Comment by peshi** [comment]
@tulbox How did you solve 1. ?

**Comment by mjrussell** [comment]
@tulbox yup you got it. Let me know if you figure it out

**Comment by mjrussell** [comment]
Closing, feel free to re-open if you are still having issues

**Comment by tulbox** [comment]
Oops. Sorry. Yes, figured out as per above.
