### ISSUE TITLE
Redirect does not include hash/fragment portion of URL

### ISSUE THREAD

**Issue by tlrobinson** [mjrussell/redux-auth-wrapper#121]
If the current URL contains a hash/fragment, i.e. `/foo#bar`, it is not included in the `redirect` query param (assuming `allowRedirectBack` is enabled).

Expected: `/login?redirect=%2Ffoo%23bar`
Actual: `/login?redirect=%2Ffoo`

Here's a workaround (assuming `routerActions.replace` is your existing `redirectAction`)

```
UserAuthWrapper({
    // ...
    redirectAction: (location) =>
        routerActions.replace({
            ...location,
            query: {
                ...location.query,
                redirect: location.query.redirect + (window.location.hash || "")
            }
        })
})
```

**Comment by mjrussell** [comment]
Good point, we are definitely not encoding that either. Should be similar to #111. Just to be clear, the expected should be `/login?redirect=%2Ffoo%23bar` right? (Not `%2F` which is `/`)

**Comment by tlrobinson** [comment]
Oops, yeah `%23`, fixed.

**Comment by mjrussell** [comment]
@tlrobinson just fixed this on master, going to see if there are any other issues to resolved and will get a new version out that supports this
