### ISSUE TITLE
Include option to always check the authenticating selector

### ISSUE THREAD

**Issue by jamespedid** [mjrussell/redux-auth-wrapper#124]
Hello, currently it is set up so that if the isAuthorized predicate evaluates to true, it ignores the isAuthenticating check entirely and short-circuits. I see where this can be valuable, but I am running into the reverse issue where I am expecting the authentication state to change by dispatching an action, but the redux auth wrapper is beating the authenticating selector to the punch and it's causing the component to use the state before the loading action.

Perhaps you can suggest a workaround, but I found this behavior to be a little quirky and I would like at least an option to always consider the authenticating selector over the isAuthorized bit.

I can do a PR if needed.

**Comment by mjrussell** [comment]
@jamespedid I think a simple workaround for this would be to make your isAuthenticated/authorized check be based on the "isAuthenticating" as well. So if you normally have:
```js
const UserIsAuthenticated = UserAuthWrapper({
  authSelector: state => state.user.data,
  authenticatingSelector: state => state.user.isLoading,
  LoadingComponent: Loading,
  redirectAction: routerActions.replace,
  wrapperDisplayName: 'UserIsAuthenticated'
})
```

And want the authenticating to have "priority", then use `&&` in the authSelector:
```js
const UserIsAuthenticated = UserAuthWrapper({
  authSelector: state => state.user.data && state.user.isLoading,
  authenticatingSelector: state => state.user.isLoading,
  LoadingComponent: Loading,
  redirectAction: routerActions.replace,
  wrapperDisplayName: 'UserIsAuthenticated'
})
```

**Comment by mjrussell** [comment]
@jamespedid did this work for you? Im going to close this but feel free to re-open if necessary.
