### ISSUE TITLE
FailureComponent: why not (state, ownProps) => Component { ...props } ?

### ISSUE THREAD

**Issue by alexandru-tomescu** [mjrussell/redux-auth-wrapper#126]
I want to redirect the user to a login page with a redirect variable (to the first page, when the login is succesfully) but i don't know how this can be possible. If i pass failureRedirectPath?redirect=encoded_base_64_url (/login?redirect=encoded_base_64_url), or /login?var=value the component's (Login) constructor doesn't even execute, because the url is not splitted in pathName and query: { params, search, etc }

Thank you

**Comment by mjrussell** [comment]
Sorry Im having trouble following you. Are you saying that you would like to change the FailureRedirectPath to more like a FailureRedirectLocation (or support both) where you can add on an additional query param of your choice?

As a workaround, I think you could do the following:
```js
const UserIsAdmin = UserAuthWrapper({
  failureRedirectPath: '/login',
  predicate: user => user.isAuthenticated,
  redirectAction: (newLoc) => (dispatch) => {
     dispatch(replace({
       ...newLoc,
       query: { // need to not lose the `redirect` query param
         ...newLoc.query,
         customVar: "customValue"
       },
     }));
  },
  ...
})
```

**Comment by alexandru-tomescu** [comment]
Basically, i want to have the following workflow:
1 - User is not logged in and goes to a protected page (with params)
2 - User is redirected to /login (and previous url with params are in the url as a "redirect" param)
3 - User logs in and he is redirected to the first url he wanted to access.
Is this clear ?

Now it's everything ok, but the last redirect doesn't work, so i have a default hardcoded url.

Thank you :)

**Comment by mjrussell** [comment]
@alexandru-tomescu hm thats exactly what this library provides. Maybe you didnt **also** apply redux-auth-wrapper to your Login component to send it back. Check out how the loading example does this:
https://github.com/mjrussell/redux-auth-wrapper/blob/master/examples/loading/app.js#L40-L63

**Comment by mjrussell** [comment]
@alexandru-tomescu Did my suggestion work for you? Were you missing the wrapper on the login?

**Comment by alexandru-tomescu** [comment]
Sorry @mjrussell , didn't try yet. I will close this issue and notify you as soon as i will check.
