### ISSUE TITLE
Router redirect feature incompatible with React Router v4.0.0-beta.7

### ISSUE THREAD

**Issue by m-allanson** [mjrussell/redux-auth-wrapper#127]
The latest release of React Router causes the 'use router for redirect if no redirectAction specified' feature to break.

From the [React Router release notes](https://github.com/ReactTraining/react-router/releases/tag/v4.0.0-beta.7)

> Split `context.router` into two parts: `context.history` and `context.route`

This causes [L126](https://github.com/mjrussell/redux-auth-wrapper/blob/4e0145bf55cabdd4597afa41241fd068ef640c99/src/index.js#L126) and [L130](https://github.com/mjrussell/redux-auth-wrapper/blob/4e0145bf55cabdd4597afa41241fd068ef640c99/src/index.js#L130) to error when using `redux-auth-wrapper` without a `redirectAction` and with `react-router v4.0.0-beta.7`

**Comment by mjrussell** [comment]
Yeah I figured there is some new work to be done with React Router 4, related to #112 but actually some new code changes. I'll probably have to support two separate versions unfortunately, unless I do some attempt at trying the v3, then the v4, and then failing
