### ISSUE TITLE
Extra location change actions dispatched for protected route

### ISSUE THREAD

**Issue by patrickgaskill** [mjrussell/redux-auth-wrapper#130]
When I try to go to `/attendance` directly from the address bar while I'm authenticated, I'm seeing the following actions:

    action @ 15:30:58.516 persist/REHYDRATE
    core.js:97 action @ 15:30:58.648 @@router/LOCATION_CHANGE
    core.js:97 action @ 15:30:58.678 @@router/LOCATION_CHANGE
    core.js:97 action @ 15:30:58.686 @@router/LOCATION_CHANGE

The three LOCATION_CHANGE actions are doing this:

    POP /attendance
    REPLACE /login
    REPLACE /attendance

So my question is, if the user is already authenticated, are all of those LOCATION_CHANGEs necessary? It seems like it's causing components to mount and unmount an extra time, which is interacting badly with a third-party JS library I'm trying to integrate. Removing the `UserIsAuthenticated` wrapper from my `App` route lets everything behave as expected.

I have wrappers and a route structure like so:

    const UserIsAuthenticated = UserAuthWrapper({
      authSelector: state => state.user,
      authenticatingSelector: state => state.user.isLoading,
      redirectAction: routerActions.replace,
      wrapperDisplayName: 'UserIsAuthenticated',
      predicate: user => user.token !== null,
    });

    const UserIsNotAuthenticated = UserAuthWrapper({
      authSelector: state => state.user,
      authenticatingSelector: state => state.user.isLoading,
      redirectAction: routerActions.replace,
      wrapperDisplayName: 'UserIsNotAuthenticated',
      failureRedirectPath: (state, ownProps) => ownProps.location.query.redirect || '/',
      predicate: user => user.token === null,
      allowRedirectBack: false,
    });

    <Route>
        <Route path="login" component={UserIsNotAuthenticated(LoginWrapper)} />
        <Route name="Home" path="/" component={UserIsAuthenticated(App)}>
          <IndexRoute component={Home} />
          <Route name="Attendance" path="attendance" component={Attendance}>
            <Route name="Activity" path="activity" component={Activity} />
          </Route>
      </Route>
    </Route>

And for completeness, here is my `createStore`:

    const configureStore = browserHistory => {
      const store = createStore(
        rootReducer,
        {},
        compose(
          autoRehydrate(),
          applyMiddleware(
            thunk,
            api,
            unauthorized,
            routerMiddleware(browserHistory),
            createActionBuffer(REHYDRATE),
            createLogger({ collapsed: true }),
          ),
          DevTools.instrument(),
        )
      );

**Comment by mjrussell** [comment]
@patrickgaskill what is your initial value of `state.user.isLoading`? It looks like maybe your protected route is returning false for both the auth selector and authenticating, and then redirecting the user to log in and finally back after the auth check (or whatever you are using to populate the store) succeeds.

Could you initialize your user reducer to return true for `state.user.isLoading` and only false after the call succeeds?

**Comment by patrickgaskill** [comment]
Here's my user reducer:

    const initialState = {
      roles: [],
      token: null,
      isLoading: false,
    };

    const user = (state = initialState, action) => {
      switch (action.type) {
        case LOGIN_REQUEST:
          return { ...initialState, isLoading: true };
        case LOGIN_SUCCESS:
          const { roles, token } = action.response;
          return { roles, token, isLoading: false };
        case LOGIN_FAILURE:
        case USER_LOGOUT:
          return initialState;
        default:
          return state;
      }
    };

**Comment by mjrussell** [comment]
Yeah so my recommendation for not having the extra redirect would be to set `isLoading` to true in the initial state

**Comment by mjrussell** [comment]
Sorry missed your last comment when I posted my response. You may want a default state vs an initial state and only set the isloading in the initial when the state is undefined

**Comment by patrickgaskill** [comment]
@mjrussell Sorry, there's still an issue here. Having `user.isLoading` always set to true does prevent the extra `LOCATION_CHANGE` actions from dispatching when I refresh the page. However, if I log out, I'm not redirected to `/login` anymore, and logging in doesn't redirect me back to `/`. I tried just removing the use of `authenticatingSelector` completely, which lets the redirects work but I'm back to having extra actions fire on refresh.

**Comment by mjrussell** [comment]
Yeah I dont recommend setting `isLoading` to true all the time, you just need to change your initial state and how you clear it:

```js
const initialState = {
  roles: [],
  token: null,
  isLoading: true,
};

const loggedOutState = {
 ...initialState,
 isLoading: false,
};

const user = (state = initialState, action) => {
  switch (action.type) {
    case LOGIN_REQUEST:
      return { ...loggedOutState, isLoading: true };
    case LOGIN_SUCCESS:
      const { roles, token } = action.response;
      return { roles, token, isLoading: false };
    case LOGIN_FAILURE:
    case USER_LOGOUT:
      return loggedOutState;
    default:
      return state;
  }
};
```

**Comment by patrickgaskill** [comment]
Gotcha, I see what you meant now. Thanks, that seems to work!
