### ISSUE TITLE
Flickering issue

### ISSUE THREAD

**Issue by jozsi** [mjrussell/redux-auth-wrapper#131]
Hello,

Give the code below, I expect that if the user is going on `/login` and is authed, should be taken to `/`. However, I see `/login` being rendered monetarily, before the redirect happens.

```js
import { UserAuthWrapper } from 'redux-auth-wrapper';
import { routerActions } from 'react-router-redux';
import Main from './components/Main';
import Home from './containers/Home';
import Login from './containers/Login';

const UserIsAuthenticated = UserAuthWrapper({
  authSelector: state => state.user,
  authenticatingSelector: state => !state.hydrated,
  predicate: user => user.token,
  redirectAction: routerActions.replace,
  allowRedirectBack: false,
});

const UserIsNotAuthenticated = UserAuthWrapper({
  authSelector: state => state.user,
  authenticatingSelector: state => !state.hydrated,
  predicate: user => !user.token,
  redirectAction: routerActions.replace,
  allowRedirectBack: false,
  failureRedirectPath: '/',
});

const routes = {
  path: '/',
  component: Main,
  childRoutes: [
    { path: 'login', component: UserIsNotAuthenticated(Login) },
  ],
  indexRoute: { component: UserIsAuthenticated(Home) },
};

export default routes;
```

Is it a bug or a misconfiguration?

Thanks!

P.S.: `state.hydrated` is a boolean, representing if persisted data was read from the local storage.

**Comment by mjrussell** [comment]
It sounds similar to https://github.com/mjrussell/redux-auth-wrapper/issues/130 although you are using the authenticating selector for hydration.

When `state.hydrated` returns false does that mean you've also checked to see if the user is authed? It sounds like that is being set to false before you have set the `state.user` in your store. 

Im not quite sure how you are checking if the user already has a valid cookie/token, but if you have a separate call to determine if the user is authenticated from a previous then you need this call to also update your store accordingly and use it in the authenticating selector.

**Comment by jozsi** [comment]
I have an initial state like this:
```json
{
  "hydrated": false,
  "user": {}
}
```

This is going to be hydrated with persisted data (if exists):
```json
{
  "hydrated": true,
  "user": {
    "token": "JWT token here",
    "name": "Jozsi"
  }
}
```

So by the time `state.hydrated` becomes true, I can decide:
1. if `state.user.token` => we are authorized
2. else if `!state.user.token` => we are not authorized

From my understanding, `redux-auth-wrapper` waits in the "loading state" while `authenticatingSelector` is true, then evaluates `authSelector` and `predicate`. The implementation above should respect this idea.

It can be reproduced [here](https://github.com/jozsi/wealthor):
1. `ln -s config.sample.js config.js`, `npm install`, `npm run dev` 
2. `http://localhost:3001`
3. set the `reduxPersist:user` key in `localStorage` to `{"email":"jozsi@tracid.ro","firstName":"Jozsi","lastName":"Gergely","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4YjQ0MDk3MDQ3NTQ1MTlkYmVjMmI2MiJ9.QbERgoO1O47CornUXOcgbJzaP_0w3E1pjYmPBuX18T8","id":"58b4409704754519dbec2b62"}`
4. `http://localhost:3001/login`

It will momentarily display the login page, however, that shouldn't be rendered at all (the `LoadingComponent` which is `null` should be rendered, and right after be redirected to `failureRedirectPath`)

**Comment by mjrussell** [comment]
@jozsi sorry for being slow to respond. I haven't forgotten about this, just going to try and finish the RRv4 and then get back to helping you with your issue. Appreciate the linked repo for reproducing the issue

**Comment by jozsi** [comment]
@mjrussell - meanwhile I migrated to `react-router v4`, eagerly awaiting on `redux-auth-wrapper` for it! Let's hope `react-router-redux v5` won't have lot's of breaking changes until it gets out of alpha and beta.

You can eventually use an [older tree](https://github.com/jozsi/wealthor/tree/ab9a8ed8ff1d000b496d05a6e4ad38b9618846f4) of the aforementioned project, in order to repro.

**Comment by mjrussell** [comment]
@jozsi now that 2.0 is pretty stable, Im thinking it makes sense to upgrade your project first and see if you are still having the same problem. If so, I'll have a lot more time now to help figure it.

**Comment by amaschas** [comment]
I'm having this same problem in the latest version (2.0-beta). I'm also using a hydration state value, which I use as the `authenticatingSelector` that default to `true`. It only gets set false at case `REQUEST_AUTH_TOKEN_SUCCESS`, yet I'm still seeing the login screen briefly.

I'm using the setup from these docs: https://mjrussell.github.io/redux-auth-wrapper/docs/Getting-Started/ReactRouter4.html

The other issue I'm encountering is that if you have two routes like `/foo` and `/foo/bar`, and you type the latter into the address bar instead of navigating via the v4 router `Link` component, you get redirected first back to login, then to the redirect path for `UserIsNotAuthenticated`.

The problem appears to be, again, that when you first hit the authentication check, it's false, which kicks off the redirection. I was under the impression that the `authenticatingSelector` behavior would prevent this.

**Comment by mjrussell** [comment]
@amaschas could you share your routes and the wrappers?

**Comment by ammoto** [comment]
@jozsi how do you set state.hydrated, in other words where do you check if  if persisted data was read from the local storage?

**Comment by jozsi** [comment]
@mjrussell - great job there, I'll definitely try it out in the near future!

@ammoto - I'm using [redux-persist](https://github.com/rt2zz/redux-persist) in it's most [simple form](https://github.com/jozsi/mystash/blob/bd2a902c2f4eff04240227f840b60afa4dd8278e/src/reducers/hydrated.js).

**Comment by akkhan20** [comment]
any news on this? Home page just flashes before redirected to Login

**Comment by mjrussell** [comment]
@akkhan20 I haven't seen an example with v2.x have this problem. If you do, please make a new issue with a reproducible test/repo.

Im going to close this due to inactivity for now
