### ISSUE TITLE
Problems integrating UserAuthWrapper into react-boilerplate

### ISSUE THREAD

**Issue by LearningDave** [mjrussell/redux-auth-wrapper#132]
Hi, i'm trying to add this great repo inside my project which is based on react-boilerplate.

I tried to add the auth wrapper function "UserIsAuthenticated" inside my container but im running into the following warning and it doesn't redirect to /login like it should.

> Warning: Failed prop type: Invalid prop `authData` of type `function` supplied to `UserIsAuthenticated(HomePage)`, expected `object`.
    in UserIsAuthenticated(HomePage) (created by Connect(UserIsAuthenticated(HomePage)))
    in Connect(UserIsAuthenticated(HomePage)) (created by Connect(Connect(UserIsAuthenticated(HomePage))))
    in Connect(Connect(UserIsAuthenticated(HomePage))) (created by RouterContext)
    in div (created by styled.div)
    in styled.div (created by App)
    in App (created by AppWithProgressBar)
    in div (created by AppWithProgressBar)
    in AppWithProgressBar (created by RouterContext)
    in RouterContext (created by Router)
    in ScrollBehaviorContext (created by Router)
    in Router
    in IntlProvider (created by LanguageProvider)
    in LanguageProvider (created by Connect(LanguageProvider))
    in Connect(LanguageProvider)
    in Provider

AuthWrapper:
```
import { UserAuthWrapper } from 'redux-auth-wrapper';
import { routerActions } from 'react-router-redux';
import { makeSelectCurrentUser } from 'Redux/Selectors/user';

// Redirects to /login by default
export const UserIsAuthenticated = UserAuthWrapper({
  failureRedirectPath: '/login',
  authSelector: () => makeSelectCurrentUser(), // how to get the user state
  redirectAction: routerActions.replace, // the redux action to dispatch for redirect
  wrapperDisplayName: 'UserIsAuthenticated', // a nice name for this auth check
});
```

HomePage Container:

```
...
import { UserIsAuthenticated } from './authWrapper'
...
// Wrap the component to inject dispatch and state into it
export default connect(mapStateToProps, mapDispatchToProps)(UserIsAuthenticated(HomePage));
```

I tried the solutions which were offered on similar issues, sadly i couldnt make it work for my project.

@mjrussell  Can you or anyone take a look and help me out please :)

**Comment by mjrussell** [comment]
> Warning: Failed prop type: Invalid prop authData of type function supplied to UserIsAuthenticated(HomePage), expected object

Sounds like the issue is right there. Presumably your `makeSelectCurrentUser()` is returning a function there. Probably you want to change the authSelector line to:
```js
export const UserIsAuthenticated = UserAuthWrapper({
  authSelector: makeSelectCurrentUser(), // how to get the user state`
  ...
})
