### ISSUE TITLE
Show/Hide components

### ISSUE THREAD

**Issue by fgiarritiello** [mjrussell/redux-auth-wrapper#134]
Hello, 

I would like to show/hide components based on user's roles. Now I understand how that can be done directly on the component class but I would like to keep the component as generic as possible so I would want to apply the wrapper at the container level. The code below is an extract of a container I created. Essentially, what I would like is to show/hide the add button in the PageHeader based on the truthy of the prop 'add'. Is there a way to do this with the wrapper?
Thanks

Ex:
```
export class ListUsersPage extends React.Component {
    onAddNewUser() {
      browserHistory.push('/users/create');
    }
    render() {
      return (
        <div>
          <PageHeader
             add onAdd={this.onAddNewUser}
          />
        </div>
      );
    }
}
```

**Comment by mjrussell** [comment]
Hmm Im not sure you need redux-auth-wrapper on the button here, but I'll provide two different approaches:

1. Using redux-auth-wrapper

The idea here is to pass through the component from the container to the PageHeader. This is a common pattern when you use more and more higher order components but can be a little bit noisy.
```js
import AddButton from 'addButton.js';

const AuthScopedAddButton = UserAuthWrapper({
  authSelector,
  predicate,
  FailureComponent: null,
});


export class ListUsersPage extends React.Component {
    onAddNewUser() {
      browserHistory.push('/users/create');
    }
    render() {
      return (
        <div>
          <PageHeader
             addButton={AuthScopedAddButton}
             onAdd={this.onAddNewUser}
          />
        </div>
      );
    }
}
```
Then you can just render the `addButton` and pass in the `onAdd` function. The `PageHeader` component has no knowledge about wether or not the button will be displayed or not.

2. Not using redux-auth-wrapper

It seems like you could connect the user data in the `ListUsersPage` and then apply the predicate that you use for your other auth checks as the bool value `add` and then just have a conditional render inside your `PageHeader` or you can make that a condition on the `onAdd` property being passed in. This would look like:

@connect((state) => ({ userData: authSelector }))
export class ListUsersPage extends React.Component {
    onAddNewUser() {
      browserHistory.push('/users/create');
    }
    render() {
      return (
        <div>
          <PageHeader
             add={hasRole(this.props.userData)}
             onAdd={this.onAddNewUser}
          />
        </div>
      );
    }
}
```

Then in the page header, when rendering in jsx do `this.props.add && <button onClick={this.props.onAdd} />`

**Comment by fgiarritiello** [comment]
@mjrussell Options #2 is exactly what I did in my case. At the same time I'm also using the auth wrapper to make sure the user without the right role can access a route.
Thanks
