### ISSUE TITLE
URL Module error on React Native

### ISSUE THREAD

**Issue by mquestionable** [mjrussell/redux-auth-wrapper#136]
Hello,

I added redux-auth-wrapper and tried to run it in the code but it says following error:
UnableToResolveError: Unable to resolve module `url` from `.../node_modules/redux-auth-wrapper/lib/index.js`. I checked and there is no url module in node_modules.

I'm using react-native with react-native-router-flux. What should I do?

Thanks!

**Comment by mjrussell** [comment]
crap, good point. The url module is only available as an import like that in browsers...That was added in 1.0. Im curious if 0.10 works for you. 

I think I'm going to have to redo how the redirect and location parsing works to support react router v4 so maybe I can improve it for react native as well. Currently there aren't any tests for react native so its easy to accidentally break compatibility. Maybe I can try to put one together after I get #133 in

**Comment by mquestionable** [comment]
Now it doesn't fail on missing url module but it's failing on index.js:146:38 because probably it's not meant to use react-native-router flux but react-router?

**Comment by piuccio** [comment]
I've just tried with

```js
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-router-native": "4.1.1",
    "react-router-redux": "5.0.0-alpha.6",
    "redux": "3.6.0",
    "redux-auth-wrapper": "1.1.0",
```

and I get the error `UnableToResolveError: Unable to resolve module 'url'`

**Comment by piuccio** [comment]
by the way as a workaround, it works if you install `url` and `query-string` in your project

```
npm install --save --save-exact url query-string
```
