### ISSUE TITLE
Can't dispatch an additional redux action on redirect

### ISSUE THREAD

**Issue by romanveryovkin** [mjrussell/redux-auth-wrapper#137]
From the docs looks like there is a possibility to dispatch an additional redux action on redirect, something like that:
```js
const UserIsAdmin = UserAuthWrapper({
  failureRedirectPath: '/app',
  predicate: user => user.isAdmin,
  redirectAction: (newLoc) => (dispatch) => {
     dispatch(replace(newLoc));
     dispatch(addNotification({ message: 'Sorry, you are not an administrator' }));
  },
  ...
})
```

but if take a look into the sources of the UserAuthWrapper, then can see, that `redirectAction` property directly inserted into the dispatch method in the mapDispatchToProps function. Therefore I get this error (if use the example from the docs):

`Error: Actions must be plain objects. Use custom middleware for async actions.`

**Comment by mjrussell** [comment]
In order for this to work you need to use the redux-thunk middleware. This is mentioned in the docs, right above the example:
> To do this, you can chain the redirectAction parameter using redux-thunk middleware

You can view the redux-thunk repo [here](https://github.com/gaearon/redux-thunk)] for instructions on how to add it to your project. You can also look at the [loading example](https://github.com/mjrussell/redux-auth-wrapper/blob/master/examples/loading/app.js#L32) for an example using `redux-thunk` and `redux-auth-wrapper`

**Comment by msman** [comment]
sorry, the [https://github.com/mjrussell/redux-auth-wrapper/blob/master/examples/loading/app.js#L32](url) page is NOT AVAILABLE!

**Comment by mjrussell** [comment]
@msman Yeah that was to the v1 examples. This is spelled out in the docs - https://mjrussell.github.io/redux-auth-wrapper/docs/AdvancedUsage/Redux.html#using-react-router-redux-or-redux-router-and-dispatching-an-extra-redux-action-in-the-wrapper
