### ISSUE TITLE
Nested Routes Not Working in react-router v4

### ISSUE THREAD

**Issue by gtwilliams03** [mjrussell/redux-auth-wrapper#138]
Thank you for this package - it works well!  I am probably doing something wrong that is very basic with the `UserIsAuthenticated` example from your docs.

Here are my two example auth components:

```
export const UserIsAuthenticated = UserAuthWrapper({
  authSelector: state => state.account, // how to get the user state
  redirectAction: routerActions.replace, // the redux action to dispatch for redirect
  wrapperDisplayName: 'UserIsAuthenticated', // a nice name for this auth check
  predicate: account => account.isAuthenticated
})
```

When I use a basic route with the `UserIsAuthenticated` component, it works fine and displays the MainViewContainer component:

```
<Route path='/main' component={UserIsAuthenticated(MainViewContainer)} />
```

However, since I want to nest several routes inside the logged in area of the site, I tried to do this and it throws an error:

```
export const AuthenticatedRoute = UserIsAuthenticated((props) => React.cloneElement(props.children || {}, props));

<Route component={AuthenticatedRoute}>
  <Route path='/main' component={MainViewContainer} />
</Route>
```

I get one error and one warning doing this:

```
Warning: You should not use <Route component> and <Route children> in the 
same route; <Route children> will be ignored

Uncaught (in promise) Error: Element type is invalid: expected a string (for built-in 
components) or a class/function (for composite components) but got: undefined. 
You likely forgot to export your component from the file it's defined in.
```

Am I doing something wrong - or is this a bug when using v4?

**Comment by mjrussell** [comment]
@gtwilliams03 you cant nest routes in react router v4. They removed that completely (hence the first warning). The second is because the children prop is no longer populated via react router v4 so it fails clone element. Im still working on best practices with redux-auth-wrapper and react router v4, but you could probably have a non-exact matching path which protects several routes to achieve what you are trying in react router v4

**Comment by gtwilliams03** [comment]
Thank you for your comment!  Much appreciated.  I figured I was missing something very basic.

Out of curiousity, when you say:

> you could probably have a non-exact matching path which protects several routes

What does that look like?

I definitely can just put the `UserIsAuthenticated` component on all of my routes also - it's just not as pretty to look at :)

**Comment by gtwilliams03** [comment]
As I think about this, are you saying that a list of routes like this would all be protected by the first route?

```
<Route path='/main' component={UserIsAuthenticated(MainViewContainer)} />
<Route exact path='/main' component={MainViewContainer} />
<Route path='/main/sub-route-1' component={SubContainer1} />
<Route path='/main/sub-route-2' component={SubContainer2} />
<Route path='/main/sub-route-3' component={SubContainer3} />
<Route path='/main/sub-route-4' component={SubContainer4} />
<Route path='/main/sub-route-5' component={SubContainer5} />
```

**Comment by mjrussell** [comment]
@gtwilliams03 yeah except you probably dont want both of the first two lines since it will show two copies of the main view. You might even be able to do something like:

```js
const Empty = () => null;

<Route path='/main' component={UserIsAuthenticated(Empty)} />
<Route exact path='/main' component={MainViewContainer} />
<Route path='/main/sub-route-1' component={SubContainer1} />
<Route path='/main/sub-route-2' component={SubContainer2} />
<Route path='/main/sub-route-3' component={SubContainer3} />
<Route path='/main/sub-route-4' component={SubContainer4} />
<Route path='/main/sub-route-5' component={SubContainer5} />
```

The first component in this case is only provided auth to anything with a `/main` path

**Comment by gtwilliams03** [comment]
This works for me.  The downside of the `Empty` is far outweighed by how much cleaner the routes look.  Thank you for the help!

**Comment by gtwilliams03** [comment]
@mjrussell Just one additional comment - your proposed solution above is working well in my test app - the only issue is that any hot module replacement on protected routes causes the hot reload to push back to the login route.  So I just commented out this line when I'm developing and it hot reloads nicely

```
<Route path='/main' component={UserIsAuthenticated(MainViewContainer)} />
```

I haven't figured out a way to preserve the authentication and routing during dev.  So I just turned it off :)
