### ISSUE TITLE
Optimize options to be isolated with react-router or more friendly with other routers

### ISSUE THREAD

**Issue by Stupidism** [mjrussell/redux-auth-wrapper#140]
Now, I succeed to use this repo without react-router. But it's kind of a [trial](https://github.com/mjrussell/redux-auth-wrapper/pull/139).
I've proposed [PR](https://github.com/mjrussell/redux-auth-wrapper/pull/139) with docs for other routers, so I think it means `redux-auth-wrapper` should change a little bit to be itself but not `react-router-redux-auth-wrapper`

**Comment by mjrussell** [comment]
Thanks, I think Im actually going to do this very thing in order to get #133 to work. It'll be some breaking changes but I think thats the only way to be flexible and support different cases like this.
