### ISSUE TITLE
The prop `location.pathname` is marked as required

### ISSUE THREAD

**Issue by JuHwon** [mjrussell/redux-auth-wrapper#142]
I found an issue when the wrapped component has a property called `location`.

My Auth wrapper looks like this
```javascript
import { UserAuthWrapper as authWrapper } from 'redux-auth-wrapper';
import { selectUserRole } from 'containers/App/selectors';
import { ROLE_ADMIN } from 'containers/App/constants';
import { redirect } from 'containers/App/actions';

export const UserIsAdmin = authWrapper({
  authSelector: (state) => ({ role: selectRoleSelector(state) }),
  redirectAction: () => redirect('/'),
  wrapperDisplayName: 'UserIsAdmin',
  predicate: (data) => data.role === ROLE_ADMIN,
});
```

then i got a component with the property location
```javascript
MyComponent.propTypes = {
  ...
  location: PropTypes.shape({...}).isRequired,
}
```

Then i do get the following error message
```
Warning: Failed prop type: The prop `location.pathname` is marked as required in `UserIsAdmin(MyComponent)`, but its value is `undefined`.
```

I did not look much into the code, though could it be optimised so that one is not limited to not use a prop called location? e.g. props with a project prefix or something?

**Comment by mjrussell** [comment]
Its trying to use the location property from react router, which is how it gets access to the url path and redirect. Are you not using react router? The breaking changes coming for #133 might enable this type of thing since I want to make it more flexible for other routing options

**Comment by JuHwon** [comment]
ahhh, its because of react-router. i do get it now. 
i just was confused, and felt kinda limited since i could not use a property called `location` (in my location management component). Since react-router does not care when i overwrite it, the issue popped up when i implemented redux-auth-wrapper. i think i can close this issue now since there is a PR fixing this issue anyway.

Also to answer your question: yes i am using react-router though as u can see i am using my own redirect action which gets handled by my custom redux middleware.
