### ISSUE TITLE
Migrate from React.PropTypes to prop-types

### ISSUE THREAD

**Issue by peshi** [mjrussell/redux-auth-wrapper#143]
Note: React.PropTypes is deprecated as of React v15.5. Please use the prop-types library instead.
https://facebook.github.io/react/docs/typechecking-with-proptypes.html

**Comment by mjrussell** [comment]
Resolved in #147

**Comment by mjrussell** [comment]
Released in 1.1.0

**Comment by peshi** [comment]
Perfect! Thank you!
