### ISSUE TITLE
Question: Server Rendering with Router Context

### ISSUE THREAD

**Issue by newbreedofgeek** [mjrussell/redux-auth-wrapper#146]
Hello,

I'm using this utility with a server side rendered react+redux+react-router app, I read the README section relating to getting it to work with SSR but I'm unable to configure it with my setup.

My setup:
I specify my routing programmatically like so.
```
import Home from 'containers/Home';
import { UserIsAuthenticated } from 'lib';

const HomeRoute = {
  component: UserIsAuthenticated(Home)
};

export default HomeRoute;
```

I use a redirect based auth selector like so (basically redirect to a login route if no state.admin exists - I persist this state on the server)
```
export const UserIsAuthenticated = UserAuthWrapper({
  authSelector: state => state.admin,
  redirectAction: routerActions.replace,
  wrapperDisplayName: 'UserIsAuthenticated'
});

```

On my server side code, I render the app out as html using RouterContext like so:
```
let html = ReactDOMServer.renderToString(
        <Provider store={store}>
          <RouterContext {...renderProps} />
        </Provider>
);
```

Unfortunately any React Router routes protected via UserIsAuthenticated() do not get server rendered, they just appear as empty divs. 

For e.g. the route above is the home root which available via "mydomain.com/", this is just rendered empty as my component that outputs {this.props.children} has an empty this.props.children...

Any help is making this work in my app code above?

Thanks very much...

**Comment by mjrussell** [comment]
Hm, I dont really have experience with SSR so I dont think I'll be much help, but I'll try...

You can get empty divs when the redirect was "supposed" to happen but didn't. Like if your `state.admin` return `null` or `{}` (which is what the default predicate checks against).

So then it would make sense that renderToString returns empty divs here. Im not sure what the right solution is though, it seems like you need to perform the redirection on the server (using `onEnter` or some other server side router redirection)

**Comment by sleungcy** [comment]
It looks like the server have to send a redirect response if react-router determined a redirection is needed. 

```
match({ routes: createRoutes({store, message, connect, first: { time: false }}), location: options.url  }, (error, redirectLocation, renderProps) => {
        if (error) {
          result.error = error;
        } else if (redirectLocation) {
          result.redirect = redirectLocation.pathname + '?' + redirectLocation.search
       } else {
           // call renderToString and insert the resulting app to the response html
       }
```

**Comment by mjrussell** [comment]
@newbreedofgeek did my response or @sleungcy help you at all? Can this be closed?
