### ISSUE TITLE
Question: How I can use AdminOrElse in component (ES6)? 

### ISSUE THREAD

**Issue by romanlex** [mjrussell/redux-auth-wrapper#151]
I use es6 and react classes. I cannot use AdminOrElse component.

```javascript
const ProjectStatus = AdminOrElse(<Dropdown />, <div className="project__status">{project.status}</div>);
```
in render I call {ProjectStatus}:
```javascript
return (
	<li id={project.id}>
		{ProjectStatus}
        </li>)
```
wrapper:
```javacript
export const AdminOrElse = (Component, FailureComponent) => UserAuthWrapper({
	authSelector: state => state.user.data,
	wrapperDisplayName: 'AdminOrElse',
	predicate: user => user.isAdmin,
	FailureComponent
})(Component);
```

But it's not work (((

**Comment by mjrussell** [comment]
You should read about the differences between components and instances of components/JSX. See the comment (and read [Dan's blog post](https://medium.com/@dan_abramov/react-components-elements-and-instances-90800811f8ca)) [here](https://github.com/mjrussell/redux-auth-wrapper/issues/91#issuecomment-260067471) for more details and [this](https://github.com/mjrussell/redux-auth-wrapper/issues/128) similar issue.
