### ISSUE TITLE
Nested multiple route wrapping

### ISSUE THREAD

**Issue by JRGranell** [mjrussell/redux-auth-wrapper#152]
Hi @mjrussell,

Great library - just having some trouble around nested wrapped routes. I'm building a portal that has multiple levels of authorisation. e.g. an authenticated user and administrator. I was hoping the following might work:

```
        <Route component={Authenticated}>
            <Route path='/portal' component={Portal}>
                {/* Authenticated */}          
                <Route path='/portal/change' components={{ content: ChangePassword }} />
               {OtherAuthenticatedRoutes}

                {/* Authenticated + Admin */}
                <Route component={AdminOnly}>
                    <Route path='/portal/admin' components={{ content: Admin }} />
                    {OtherAdminRoutes}
                </Route>
            </Route>
        </Route>
```

For brevity I have reduced the number of routes. The wrappers: 

```
const AuthenticatedUser = UserAuthWrapper({
    authSelector: (state) => state.login,
    predicate: (login) => login.isAuthenticated,
    wrapperDisplayName: 'AuthenticatedUser',
    FailureComponent: Login
});
const Authenticated = AuthenticatedUser((props: any) => React.cloneElement(props.children, props));

const AdminWrapper = UserAuthWrapper({
    authSelector: (state) => state.login,
    predicate: (login) => requireScope(login.scope, 'admin'),
    wrapperDisplayName: 'AuthorisedUser',
    FailureComponent: Unauthorised
});
const AdminOnly = AdminWrapper((props: any) => React.cloneElement(props.children, props));
```

When used in isolation or when using ```AdminWrapper(component)``` they all work. However I'm importing lots of routes and it would be great to be able to wrap them all without having to individually protect them. 

With this setup the adminOnly predicate never gets called, no errors and the 'Unauthorised' component does not show. I just get empty content. Appreciate any thoughts.

Many thanks,

JR

**Comment by mjrussell** [comment]
Sorry for the delay in responding, I think its because you are using the react router named components (i.e. `components={{ content: Admin }}`) this is going to pass the property `content` with the value being the result of rendering `Admin` to the parent Route, in this case the wrapper. So instead of doing:
```js
React.cloneElement(props.children, props);
```
I think you want
```js
React.cloneElement(props.content, props);
```

**Comment by JRGranell** [comment]
Appriciate the hint, it put me on the right path. In addition to changing the returned property I also needed to change _where_ the auth check was taking place to also be on the component. i.e change 

```<Route component={AdminOnly}>```

to

```<Route components={{ content: AdminOnly }}>```

Which makes sense and is accidentally a really nice way of managing access _to a specific part_ of a page.

Thanks,

**Comment by brijeshbhakta30** [comment]
Hi, I'm new to react and I having this route configuration for my application.

`const rootRoute = {
  childRoutes: [{
    path: '/',
    component: require('./containers/App'),
    indexRoute: { onEnter: (nextState, replace) => replace('/login') },
    childRoutes: [
      require('./routes/app'),
      require('./routes/404'),
      require('./routes/500'),
      require('./routes/forgotPassword'),
      require('./routes/login'),
      require('./routes/signUp'),
      {
        path: '*',
        indexRoute: { onEnter: (nextState, replace) => replace('/404') },
      }
    ]
  }]
};`

And I want to add validation on the "app" route which itself has child routes. Is there a way to wrap all those child routes at a single place?

**Comment by mjrussell** [comment]
@brijeshbhakta30 you can just apply the redirect wrapper to your `App` container. Either in the component definition or in your route. Since it renders the subpages as children, the validation checks will still apply to all child routes
