### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by malishahi** [mjrussell/redux-auth-wrapper#155]
Hi,

I have difficulty in understanding the documentation. e.g. not sure how authSelector works, what does it do?

authSelector: state => state.user, // how to get the user state 

I have a security component (SecurityContainer) which manages security, how can I use that in order to connect it to UserAuthWrapper in order to understand if user is authenticated or not?
My redux store provides several state variable for authenitcation like:

state.security.authenticated 
state.security.isAuthenticating
state.security.userInfo

It would be great if you could give me some hints.

Thanks.

**Comment by mjrussell** [comment]
@malishahi The authSelector was originally designed as a redux selector for the user info (whatever that might be in your app) that you would want to 1) Ensure some property of it such as authenticated or maybe authorized for some action/data and 2) pass down that information to sub components where they can be sure that they are never rendered without 1) being true.

The examples use an oversimplified state which is just essentially `state.user` where user can be null or an object with the fields `name` and `isAdmin`. In this example, `authenticated` is just true when the object is not null.

I understand that this isn't always the most natural, and it was also discussed in #157. I agree, that its a bit awkward for your use case and I think I'm going to change it for v2 (see #153).

In your case, the best thing to do is probably an `authSelector` of `state => state.security`, then use a `predicate` of `security => security.authenticated`.

Then you can add an `authenticatingSelector` as `state => state.security.isAuthenticating`

Let me know if that helps, and sorry for the delay

**Comment by malishahi** [comment]
Thanks @mjrussell. I will use based on your comments, and provide a report.

**Comment by mjrussell** [comment]
@malishahi did that work for you? Can I close this issue now?

**Comment by malishahi** [comment]
@mjrussell working fine. thanks.
