### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by cviebrock** [mjrussell/redux-auth-wrapper#161]
I'm trying to set up an app with 2.0.0-beta2 of this package.

The idea is that anything under the `/admin` URL tree is protected, and you need to sign in via `/admin/login`.  With my main App component (below), and everything else basically the same as the RR4 example from this package, I'm getting the following error:

```
Uncaught TypeError: Cannot read property 'replace' of undefined
```

This traces back to the following code in `redux-auth-wrapper/src/history4/redirect.js`:

```js
export const { connectedRouterRedirect, connectedReduxRedirect } = redirectUtil({
  locationHelperBuilder,
  getRouterRedirect: ({ history }) => history.replace
})
```

Any ideas what I'm doing wrong?

My component:

```jsx
// components/App.js

import React, { Component } from 'react';
import { BrowserRouter, Route } from 'react-router-dom';
import { userIsAuthenticated, userIsNotAuthenticated } from '../auth';
import Home from './Home';
import Login from './Login';
import Layout from './Layout';


const Authenticated = userIsAuthenticated((props) => React.cloneElement(props.children, props));
const LoginComponent = userIsNotAuthenticated(Login);

class Admin extends Component {
    render() {
        return (
            <BrowserRouter basename="/admin">
                <Layout>
                    <Route path="/login" component={ LoginComponent }/>
                    <Authenticated>
                        <Route exact path="/" component={ Home }/>
                    </Authenticated>
                </Layout>
            </BrowserRouter>
        );
    }
}

export default Admin;
```

**Comment by boaticus** [comment]
I was having a similar issue until @jwickens posted a workaround he discovered, [as he details here](https://github.com/mjrussell/redux-auth-wrapper/pull/153#issuecomment-304499034) in his reply to #153 

to summarize: everywhere in your import statement where you have `src`, use `lib` instead.

thusly:
```
import locationHelperBuilder from 'redux-auth-wrapper/lib/history4/locationHelper'
import { connectedRouterRedirect } from 'redux-auth-wrapper/lib/history4/redirect'
```

and also in your `userIsNotAuthenticated`, double check to be sure your usin the correct method of locationHelper:
`locationHelper has locationHelper.getRedirectQuery(ownProps)` 
rather than `locationHelper.getRedirectQueryParams(ownProps)`

I'm not sure if this will always be the case, or if this is truly the fix moving forward. @mjrussell could answer that better than I. But for now, this small change should help you forward with your project.

Mad props to @jwickens on discovering this.

**Comment by mjrussell** [comment]
@boaticus I do hope to fix both of those things int he examples, Im currently working on the docs and will update the examples as I go.

As for your issue @cviebrock I think its a different problem. The wrapped component (in this case LoginComponent or Authenticated) expects to be passed the `history` object (this is what the `getRouterRedirect` does) but likely your `Layout` component doesn't pass it to its children.

You can tackle this one of two ways. 

1) In your `Layout` component you can add a React.cloneElement to add the `history` property to the children

2) Add another HOC on the `Authenticated` and `LoginComponent`. You can use:
```js
import { withRouter } from 'react-router';

const Authenticated = withRouter(userIsAuthenticated((props) => React.cloneElement(props.children, props)));
const LoginComponent = withRouter(userIsNotAuthenticated(Login));
```

**Comment by cviebrock** [comment]
@boaticus Thanks for the suggestions.  I saw them in another issue in here, so I was already using the `lib` version of the imports, and the `getRedirectQuery` method.

@mjrussell Thank you!  I took your second suggestion and it appears to work.  Attempting to load `/admin` redirects me to `/admin/login?redirect=%2F`.  However, the form that I built for logging in does not appear.  If I reload that page, I see it.  So ... maybe something on the redirect is not causing the <Login> component to render?

(and apologies if these are noob questions ... I'm just getting started with React 😉  )

**Comment by mjrussell** [comment]
Can you include your `auth` file?

**Comment by cviebrock** [comment]
Yup!  (I use `state.auth` instead of `state.user` as you have in the example).


```js
import locationHelperBuilder from 'redux-auth-wrapper/lib/history4/locationHelper';
import { connectedRouterRedirect } from 'redux-auth-wrapper/lib/history4/redirect';

import Loading from './components/Loading';

const locationHelper = locationHelperBuilder({});

export const userIsAuthenticated = connectedRouterRedirect({
    redirectPath:            '/login',
    authSelector:            state => state.auth,
    authenticatingSelector:  state => state.auth.isLoading,
    AuthenticatingComponent: Loading,
    predicate:               auth => auth.data !== null,
    wrapperDisplayName:      'UserIsAuthenticated'
});

export const userIsNotAuthenticated = connectedRouterRedirect({
    redirectPath:       (state, ownProps) => locationHelper.getRedirectQuery(ownProps) || '/',
    allowRedirectBack:  false,
    authSelector:       state => state.auth,
    // Want to redirect the user when they are done loading and authenticated
    predicate:          auth => auth.data === null && auth.isLoading === false,
    wrapperDisplayName: 'UserIsNotAuthenticated'
});
```

**Comment by mjrussell** [comment]
@cviebrock sorry its been so long 😞 . Were you able to get this working? If not, could you try updating to the latest beta tag and see if this fixes your issue?

Here is the React Router 4 getting started guide: https://mjrussell.github.io/redux-auth-wrapper/docs/Getting-Started/ReactRouter4.html

**Comment by JulianJorgensen** [comment]
This issue does still seem alive. Have spent a few hours bugfixing it with no luck, but will definitely post here if I find a solution myself. 

Have already made sure my component uses withRouter HOC.
