### ISSUE TITLE
onEnter link broken in README

### ISSUE THREAD

**Issue by LiJinyao** [mjrussell/redux-auth-wrapper#163]
In README line 30:
```
 After all, we have a handy [onEnter](https://github.com/rackt/react-router/blob/master/docs/API.md#onenternextstate-replace-callback) method
```
the link is broken. Is it an API change?

**Comment by Clafouti** [comment]
The `onEnter` hook disappeared from react-router v4. [Here](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md#on-properties)'s the guide for migration.

That part of the readme should probably disappear in my opinion, or link to the [old v3 doc](https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#onenternextstate-replace-callback)

**Comment by mjrussell** [comment]
Fixed in 1.x docs in 2af791d4ed878bc223d910403aa1d1e7b94ade32 and updated in the new v2 documentation. Thanks!
