### ISSUE TITLE
Question: How would you describe a redirect back to an authenticated view from '/login'?

### ISSUE THREAD

**Issue by james-prado** [mjrussell/redux-auth-wrapper#164]
I'm a little confused how to make this kind of interaction work from a UserAuthWrapper().

The interaction I'm trying to achieve:
- User goes to /foo, (an authenticated view)
- User is redirected to /login,
- User logs in, and is redirected back to the authenticated view they initially came from (/foo)

[Repo](https://github.com/james-prado/clevermine-site)

**Comment by baahrens** [comment]
UserAuthWrapper will set a query param after redirecting from an authenticated view. (`?redirect=authenticated/view` e.g.) so in your `/login` view you can redirect based on this, after the user has logged in.  You can controll the paramName with the option `[redirectQueryParamName]`.

**Comment by james-prado** [comment]
I'm seeing the redirect property in my state (query: { redirect: "/foo" }), but how do i get my /login view to redirect to this new property?

incase I'm not making sense or describing my issue properly I made a (Repo)[https://github.com/james-prado/redux-auth-wrapper-issue]

**Comment by baahrens** [comment]
You could achieve this with `componentWillReceiveProps`, something like:
```js
componentWillReceiveProps(nextProps) {
    if (nextProps.user) router.push(nextProps.location.query.redirect)
}
```
Or, assuming your Login-ActionCreator returns a promise, do it in the then part like:
```js
handleLogin = (user, password) => {
  login(user, password)
  .then(() => router.push(nextProps.location.query.redirect))
}
```

Or what I've done recently is to wrap the Login Component in another UserAuthWrapper with the opposite behaviour. I believe you tried this in your repo with `NotAuthenticatedComponent`. The predicate would then be, that the user is *not* authenticated with the failureRedirectPath (so when the user is logged in) to `location.query.redirect`.
Adjusting your `NotAuthenticatedComponent`:
```js
export const NotAuthenticatedComponent = UserAuthWrapper({
  authSelector: state => state.user,
  redirectAction: routerActions.replace,
  predicate: state => state.user === undefined,
  wrapperDisplayName: 'UserIsNotAuthenticated',
  failureRedirectPath: state => state.location.query.redirect
})
```

Don't now about the last option. It works for sure, but might not be the intended use of the Wrapper.
Anyways, hope this helps.

**Comment by james-prado** [comment]
one more question, how would I set a default for router.location.query.redirect? If i go to /login without being redirected by an auth view, router.location.query is never created in my state, so I can't .push() to the redirect property

**Comment by baahrens** [comment]
router.location.query *should* always exist, but could be empty, so you can just do
```js
router.push(location.query.redirect || '/')
```
Something else would be lodash's get, which doesn't throw if the path doesn't resolve and lets you specify a default value:
```js
const redirectPath = ._get(location, 'query.redirect', '/')
router.push(redirectPath)
```

Ultimately you just need something to check if 'redirect' is set and fallback to your default otherwise.

**Comment by james-prado** [comment]
it _should_ exist, but it doesn't :/

instead it looks like this
```{
  user: {},
  router: {
    location: {
      pathname: '/',
      search: '',
      hash: ''
    }
  }
}```

**Comment by baahrens** [comment]
Okay, then just check for both query and redirect
```js
if (location.query && location.query.redirect) router.push(...)
```
or use lodash's get.

**Comment by mjrussell** [comment]
Hey, sorry for not responding sooner. Have you both looked at the loading example? It uses a `UserIsNotAuthenticated` in exactly [this way](https://github.com/mjrussell/redux-auth-wrapper/blob/master/examples/loading/app.js#L40-L63).

In react router 3 (history v3) the query param is not required to exist. Its non-consistency is one of the reasons it was removed in history v4

**Comment by james-prado** [comment]
Thanks @mjrussell , I took a look at the example. Turns out instead of trying to redirect from ownProps.location.query, i was trying to redirect from state.location.query which doesn't exist most of the time and was the cause of my issues.

my code: 
```
	failureRedirectPath: state =>
		state.location.query && state.location.query.redirect
			? state.location.query.redirect
			: '/',
```

solution: 
```
	failureRedirectPath: (state, ownProps) =>
		ownProps.location.query && ownProps.location.query.redirect
			? ownProps.location.query.redirect
			: '/',
```

**Comment by james-prado** [comment]
@mjrussell Ok i'm confused again. Initially I fixed the issue by following the example and using the props as a failureRedirectPath. Now I nested some components in [the repo](https://github.com/james-prado/clevermine-site) and I'm back to square 1

**Comment by mjrussell** [comment]
You are using react-router-redux alpha and history v4? Version 1.x wont work well with those, it is unsupported (although you might be able to hack around it to get it semi-stable). Check out the following PR and discussions - https://github.com/mjrussell/redux-auth-wrapper/pull/153

Im trying really hard to put the finishing touches on it so it can get out the door
