### ISSUE TITLE
Browser keeps redirecting when predicate resolves to false

### ISSUE THREAD

**Issue by tkvw** [mjrussell/redux-auth-wrapper#167]
This behaviour is easily viewable by running the basic example and adding a predicate which resolves to false. See the screenshot for the result (you can see the url change, but after a while I get a stackoverflow exception). 

![2017-06-30_00-52-34](https://user-images.githubusercontent.com/621098/27714063-0e81d408-5d2f-11e7-9c82-c31821f60c01.gif)

**Comment by tkvw** [comment]
Found it, I hadn't looked into Login.js.. There's a manual authenticated lookup and decides if a redirect should be applied, this lookup ignores the outcome of Predicate, but it's an example after all...

**Comment by mjrussell** [comment]
Yeah this would have been more easy to spot in the loading example since it has a predicate check explicit. I prefer that way and in v2 the examples only show using HOCs for both Login and the Protected route
