### ISSUE TITLE
Question: Rendering Alternate Components (Dynamic React Router)

### ISSUE THREAD

**Issue by jmenglis** [mjrussell/redux-auth-wrapper#170]
Attempting to render routes through React Router dynamically but I have a situation where I need to use alternates and cannot seem to get it to properly route.

```
export const LandingOrLoggedIn = (Component, FailureComponent) =>
  UserAuthWrapper({
    authSelector: state => state.user.LoggedIn,
    wrapperDisplayName: 'LandingOrLoggedIn',
    FailureComponent,
  })(Component);

const routes = store => {
  return {
    component: App,
    childRoutes: [
      {
        path: '/',
        component: LandingPage,
        indexRoute: {
          getComponent(location, cb) {
            LandingOrLoggedIn(
              import('app/modules/UserApp')
                .then(loadRoute(cb))
                .catch(errorLoading),
              import('app/modules/Home') 
                .then(loadRoute(cb))
                .catch(errorLoading)
            );
          },
        },
      },
    ],
  };
};

export default routes;
```

Any thoughts on how I can potentially get this working?

**Comment by mjrussell** [comment]
Just so you understand, theres no "routing" when you use the alternate components, its basically an if check wrapped around two components. 

Also the [REAMDE](https://github.com/mjrussell/redux-auth-wrapper#where-to-define--apply-the-wrappers) specifically says not to try applying an HOC (in this case `LandingOrLoggedIn`) inside a `getComponent`. Theres a high potential for weird bugs and other errors. Instead you should probably create a new component in a separate file, that imports both and applies the `LandingOrLoggedIn` to both. Then import that with `getComponent`

**Comment by jmenglis** [comment]
@mjrussell that makes sense.  I will try writing that separate component.  I racked my brain on this for a few hours late on Friday.  Probably not the best time to be writing complex code. 😆
