### ISSUE TITLE
Problem with showing a link when logged in.

### ISSUE THREAD

**Issue by Maiko1100** [mjrussell/redux-auth-wrapper#175]
Hi guys,
I have a problem, I am trying to show a logout link whenever im logged in. I created the wrapper as shown below.
```
export const visibleOnlyLoggedIn = AuthWrapper({
  authenticatedSelector: state => state.user.isLoggedIn === true,
  wrapperDisplayName: 'VisibleOnlyLoggedIn'
});
```
In my component i do the following.
I import the wrapper.
`import { visibleOnlyLoggedIn } from '../../../utils/auth';`

Then i create this constant
`const LogOutLink = visibleOnlyLoggedIn(() => <li onClick={() => logout()}>Logout</li>);
`

And this is how my header looks like.
```
      <img src={logo} alt="Logo" className="logo" />
      <ul>
        <li><Link to="/">Home</Link></li>
        <li><Link to="/counter">Counter</Link></li>
        < LogOutLink />
      </ul>
    </div>
```

It looks like its not even calling the visibleOnlyLoggedIn(() method. 
We also tried setting the authenticatedSelector default on true but that also didn't do anything.

I hope someone can help me,
Kind regards,
Maiko

**Comment by mjrussell** [comment]
Ugh sorry, there's some bugs in the docs. I'm updating them right now. It should be:

```
import connectedAuthWrapper from 'redux-auth-wrapper/connectedAuthWrapper'

export const visibleOnlyLoggedIn = connectedAuthWrapper({
  authenticatedSelector: state => state.user.isLoggedIn === true,
  wrapperDisplayName: 'VisibleOnlyLoggedIn'
});
```

Importing from `redux-auth-wrapper/authWrapper` is just an HOC that adds a component expecting the `isAuthenticated` boolean (and then performs hiding, etc). The connected wrapper uses connect to bind that with the `authenticatedSelector`.

**Comment by Maiko1100** [comment]
Thank you!!
Its working great now!
