### ISSUE TITLE
Version 2.0.0 missing main file, can't import

### ISSUE THREAD

**Issue by GeKorm** [mjrussell/redux-auth-wrapper#181]
Hello and thanks for this library
I installed v2 and tried to import using  

`import { connectedReduxRedirect } from 'redux-auth-wrapper';`

The path is unresolved. Peeking into /node_modules/redux-auth-wrapper I can't find an index.js or `main` declared in package.json

However I can use the library by doing  

`import connectedReduxRedirect from 'redux-auth-wrapper/connectedAuthWrapper';`

**Comment by GeKorm** [comment]
Huh just realized that according to [the docs](https://mjrussell.github.io/redux-auth-wrapper/docs/Migrating.html) I was supposed to  
`import { connectedReduxRedirect } from 'redux-auth-wrapper/history3/redirect'`

**Comment by mjrussell** [comment]
Yeah this is because the library supports multiple versions of history now and also allows devs to use it without even redux, so the imports have to get split up instead of rolled up into a single `index.js` file.
