### ISSUE TITLE
Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` 

### ISSUE THREAD

**Issue by shengnian** [mjrussell/redux-auth-wrapper#186]
hi, that's nice component for auth,  but in webpack 3.x, the chrome browser console output the below error:

```Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types
    in UserIsNotAuthenticated(l) (created by Connect(UserIsNotAuthenticated(l)))
    in Connect(UserIsNotAuthenticated(l)) (created by Route)```

**Comment by mjrussell** [comment]
What version are you using? Both 1.1.0 and 2.x use the proptypes package so you shouldn't be getting this error if you've upgraded

**Comment by shengnian** [comment]
@mjrussell thank you for reply, i returned the webpakc to  2.x, that's working fine. i don't know why report this warning, a little confused. check the source was not found the PropTypes for validators.
