### ISSUE TITLE
Components re-render on redirectPath

### ISSUE THREAD

**Issue by foodgy** [mjrussell/redux-auth-wrapper#188]
My problem is that on every redirect caused by redux-auth-wrapper (e. g. from auth route to login route) components are re-render.

I've implemented redux-auth-wrapper just like it's suggested in react-router v3 example:

```
export const userIsAuthenticated = connectedRouterRedirect({
  redirectPath: '/login',
  authenticatedSelector: state => state.session.user !== null,
  authenticatingSelector: state => state.session.isLoading,
  wrapperDisplayName: 'UserIsAuthenticated'
})

export const userIsNotAuthenticated = connectedRouterRedirect({
  redirectPath: (state, ownProps) =>
    locationHelper.getRedirectQueryParam(ownProps) || '/projects',
  allowRedirectBack: false,
  authenticatedSelector: state =>
    state.session.user === null && state.session.isLoading === false,
  wrapperDisplayName: 'UserIsNotAuthenticated'
})
```

And then I use both userIsNotAuthenticated and userIsAuthenticated inside layout containers like this:

```
// Auth Layout
...
import { userIsAuthenticated } from 'utils/auth'

export const AuthLayout = ({ children }) =>
  <div>
    <NavBar />
    <Container>
      {children}
    </Container>
    <ModalRoot />
  </div>

AuthLayout.propTypes = {
  children: PropTypes.node
}

export default userIsAuthenticated(AuthLayout)
```

Public layout container is the same, except it uses userIsNotAuthenticated:

```
// Public Layout
...
import { userIsNotAuthenticated } from 'utils/auth'

export const PublicLayout = ({ children }) =>
  <div>
    {children}
  </div>

PublicLayout.propTypes = {
  children: PropTypes.node
}

export default userIsNotAuthenticated(PublicLayout)
```

The problem is authorized routes are being re-rendered every time user tries to access public routes.
Example:

1. **/login**
2. Authorize
3. Redirect to **/projects**
4. Manualy navigate to any public route like **/login** or **/register**
5. Redirect to **/project** with re-render

Is there a way to escape this re-render?

**Comment by mjrussell** [comment]
Im not sure I follow, you are specifically navigating away from your `/projects` so the components are unmounted from the dom right? Then when you navigate back to `/projects` they have to be re-rendered in order to put them into the dom. React doesn't save their previous rendered state in a cache. Or are you only swapping out a piece of the page and components which are not swapped out are being re-rendered unnecessarily?

**Comment by foodgy** [comment]
@mjrussell seems legit :) Thx
