### ISSUE TITLE
v4 Documentation Clarification

### ISSUE THREAD

**Issue by gitjeff05** [mjrussell/redux-auth-wrapper#189]
In the example for [v4 for securing a route](https://mjrussell.github.io/redux-auth-wrapper/docs/Getting-Started/ReactRouter4.html#securing-a-route), it says to create one HOC, ``userIsAuthenticated`` and use that to wrap your protected components. That works just fine.

In the next section, [Redirecting From Login](https://mjrussell.github.io/redux-auth-wrapper/docs/Getting-Started/ReactRouter4.html#redirecting-from-login), it says that we want to use ``locationHelper`` to redirect our user after successful login in our component, ``userIsNotAuthenticated``. The docs go on to say:

> Luckily we can easily do both of these with our wrapper.

### Questions:
- Is this suggesting that we use the same wrapper for all components? 
- Or are we supposed to create a second HOC (notice in the examples the wrappers have two different names -- ``userIsAuthenticated`` and ``userIsNotAuthenticated``)? 
- How would those two different components be applied? 
- Are we supposed to apply the ``userIsNotAuthenticated`` wrapper around a ``<Login />`` component and the ``userIsAuthenticated`` wrapper around all of our protected routes?

I cannot make sense of this and have tried multiple ways without success.

**Comment by mjrussell** [comment]
> Luckily we can easily do both of these with our wrapper.

Yes that should read as "we can create a new wrapper", sorry about that. I can also add applying it to a Login component. This is what the example for react-router-4 does. It creates the wrappers here - https://github.com/mjrussell/redux-auth-wrapper/blob/master/examples/react-router-4/auth.js

And then applies them here - https://github.com/mjrussell/redux-auth-wrapper/blob/master/examples/react-router-4/components/App.js#L14-L22

**Comment by gitjeff05** [comment]
Ah okay, thank you @mjrussell . I will take a closer look at the code in the examples. Using what was provided in the docs caused infinite redirects and my app eventually crashed. I'll see if I can learn anything valuable in the examples to be applied in the docs.

**Comment by mjrussell** [comment]
Yeah infinite redirects can happen, and are annoying to debug at times. Usually its due to conflicting `isAuthenticated/isAuthenticating` results in your selectors for each separate wrapper. I'd definitely make sure that when your redirect to Login fires, it wont immediately fire back.

It'd probably be good to add some helpful testing code example so people can provide various state config objects and ensure that only one redirect would occur (as opposed to both happening and pinging back off each other)

**Comment by mjrussell** [comment]
I just updated the docs to hopefully make things a bit more clear. Let me know if I should close this or if there's more clarification that could be done
