### ISSUE TITLE
How can I turn off the wrapper component?

### ISSUE THREAD

**Issue by kheide** [mjrussell/redux-auth-wrapper#195]
I would like to not show the authenticating wrapper component while the authentication is loading/fetching. How can this be disabled?

**Comment by mjrussell** [comment]
@kheide Im not sure I fully understand your question. By default, if you are using the `authenticatingSelector` but don't pass in an `AuthenticatingComponent`, redux-auth-wrapper will not render anything. Maybe you currently aren't specifying the `authenticatingSelector` parameter?
