### ISSUE TITLE
demo with react router v4 is broken

### ISSUE THREAD

**Issue by eldyvoon** [mjrussell/redux-auth-wrapper#198]
ERROR in ./auth.js
Module not found: Error: Cannot resolve module 'redux-auth-wrapper/history4/locationHelper' in /Users/admin/Documents/redux-auth-wrapper/examples/react-router-4
 @ ./auth.js 10:22-75

ERROR in ./auth.js
Module not found: Error: Cannot resolve module 'redux-auth-wrapper/history4/redirect' in /Users/admin/Documents/redux-auth-wrapper/examples/react-router-4
 @ ./auth.js 14:16-63

ERROR in ./auth.js
Module not found: Error: Cannot resolve module 'redux-auth-wrapper/connectedAuthWrapper' in /Users/admin/Documents/redux-auth-wrapper/examples/react-router-4
 @ ./auth.js 16:28-78
webpack: Failed to compile.

**Comment by mjrussell** [comment]
its not broken, maybe you didn't compile the src first?
