### ISSUE TITLE
Router Router 4: show modal instead of redirect to url

### ISSUE THREAD

**Issue by williamgranli** [mjrussell/redux-auth-wrapper#202]
Is it possible to trigger an action with which shows a login modal instead of redirecting to a url?

Issue #70 describes how you can get around it with triggering an action with the redirectAction param, but this doesn't work with router v4 when I tried.

Thanks!

**Comment by mjrussell** [comment]
@williamgranli I think this was the right approach, you should be able to use `redirectAction` with react-router 4. Could you explain what didn't work?
