### ISSUE TITLE
RRv4 & SSR

### ISSUE THREAD

**Issue by oyeanuj** [mjrussell/redux-auth-wrapper#205]
Hi @mjrussell! I was finally getting to the `react-router` and `redux-auth-wrapper` upgrade party.. and had a quick question based on the docs - how do you do SSR with RAW & RRv4? 

I noticed in the docs that you only have SSR docs for RR2/3. Happy to make a PR to the docs with the answer!

**Comment by oyeanuj** [comment]
Has anyone else set up SSR with this library & RRv4? Appreciate any insights!

**Comment by mjrussell** [comment]
@oyeanuj sorry man, Im not entirely sure the best approach yet and I don't really use SSR. Happy to include docs/helpers if someone figures out a good path forward with redux-auth-wrapper for SSR and RRv4

**Comment by oyeanuj** [comment]
@mjrussell No worries, I'll take a stab soon. On the top of your head, any pointers on what might be the big problematic areas?

**Comment by ESTrainer** [comment]
@oyeanuj do you have any update on SSR?

**Comment by oyeanuj** [comment]
@ESTrainer From the little experimentation I did, it just worked out of the box. No major issues yet..

**Comment by jaybe78** [comment]
@oyeanuj Could you give us an update regarding the implementation of that library with SSR ? have you gotten any issues since your last post in May ?
You said it worked out of the box, so you did not have to do any modifications whether in your server or client code ?

**Comment by casoetan** [comment]
@jaybe78 yes. It just works out of the box. DO you have any specific issues?

**Comment by mjrussell** [comment]
Im going to close this, sounds like it works! Would appreciate any snippets people have to help others
