### ISSUE TITLE
Dispatching an Additional Redux Action on Redirect, Error: Actions must be plain objects. Use custom middleware for async actions.

### ISSUE THREAD

**Issue by bugalaws** [mjrussell/redux-auth-wrapper#208]
Hello guys, I'm implementing the Redux-Auth-Wrapper in my project, but I'm getting error on trying  additional dispatch.

Here's my Auth.js:
`import locationHelperBuilder from 'redux-auth-wrapper/history3/locationHelper';
import { connectedReduxRedirect } from 'redux-auth-wrapper/history3/redirect';
import { routerActions } from 'react-router-redux';
import addNotification from './constants/actionTypes';
import { verifyTokenIsExpired } from './tools/generic';

const locationHelper = locationHelperBuilder({});

export const userIsAuthenticated = connectedReduxRedirect({
  redirectPath: '/login',
  allowRedirectBack: false,
  authenticatedSelector: state => state.auth.isAuthenticated && !verifyTokenIsExpired(state.auth.expLocal),
  redirectAction: (newLoc) => (dispatch) => {
      dispatch(routerActions.replace(newLoc));
  },
  wrapperDisplayName: 'UserIsAuthenticated'
});`

In console I'm getting this error:
Error: Actions must be plain objects. Use custom middleware for async actions.
 
If I use redirectAction: routerActions.replace, works pretty, someone have an ideia what I do wrong ?

**Comment by mjrussell** [comment]
From the docs https://mjrussell.github.io/redux-auth-wrapper/docs/AdvancedUsage/Redux.html#dispatching-an-additional-redux-action-on-redirect

> Note: make sure you add redux-thunk to your store's middleware or else the following will not work

https://github.com/gaearon/redux-thunk

**Comment by msman** [comment]
HI, 
in the link , It tells that:
make sure you add redux-thunk to your store's middleware or else the following will not work

how can   I achieve that?

**Comment by msman** [comment]
Hi again,

I tried to implement the solution here [https://mjrussell.github.io/redux-auth-wrapper/docs/AdvancedUsage/Redux.html#dispatching-an-additional-redux-action-on-redirect](url) but I see it asks me to write different code than that on [https://mjrussell.github.io/redux-auth-wrapper/docs/Getting-Started/ReactRouter4.html](url) and I couldn't figure out how can I solve the error: **Error: Actions must be plain objects. Use custom middleware for async actions.**

So actually I am stopped!

**Comment by mjrussell** [comment]
@msman you need to add the redux-thunk middleware that I linked in the comment above to your middleware. If you don't know what a middleware is, or how to do this, I suggest you read up about redux more before trying to integrate that functionality into your project (https://redux.js.org/docs/advanced/Middleware.html). You can also ask on the reactiflux discord for more help. This isn't something specific to redux-auth-wrapper so you should be able to find lots of resources online
