### ISSUE TITLE
Don't redirect after auth

### ISSUE THREAD

**Issue by shapkarin** [mjrussell/redux-auth-wrapper#211]
in Url I see "login?redirect=%2Fprofile" but how to redirect(to profile) after auth?

**Comment by aleksandertsg** [comment]
Did you use the wrapper for Login component also ?

**Comment by shapkarin** [comment]
No... see https://github.com/mjrussell/redux-auth-wrapper/blob/master/examples/react-router-3/app.js#L46 in example, thatks
