### ISSUE TITLE
`connectedRouterRedirect` unmounting and mounting

### ISSUE THREAD

**Issue by marcdavi-es** [mjrussell/redux-auth-wrapper#212]
Hi. Thanks so much for all the time you put into this library :)

I have an issue which I thought was related to #187 but after further digging I believe it is something else.

In brief, when one of the parent components of my application (`Viewport`) gets updated, the HOC created by `connectedRouterRedirect` is unmounted along with its subtree. It is then mounted again.

This is problematic in itself, but it is a breaking bug for me as it resets component state in the subtree.

I assume `connectedRouterRedirect` must be returning a new component which appears to React to be different to the previous component.

I have a fairly vanilla setup...

```js
// Application.js

import {AuthenticatedRoute, NotAuthenticatedRoute} from 'modules/authentication';

...

render = () => (
     <Router history={history}>
        <Viewport>
          <Switch>
            <AuthenticatedRoute
              path={PATHS.HOME}
              componentToRender={Dashboard}
            />
          </Switch>
       </Viewport>
     </Router>
...


// authentication/components.js

import {routeFactory} from './factory';
import {authenticatedRoute} from './wrappers';

export const AuthenticatedRoute = routeFactory(authenticatedRoute);


// authentication/factory.js

import React from 'react';
import {Route} from 'react-router-dom';

export const routeFactory = wrapper => ({
    componentToRender,
  }) => <Route component={wrapper(componentToRender)} />
);


// authentication/wrappers.js

import {connectedRouterRedirect} from 'redux-auth-wrapper/history4/redirect';

import {Loader} from 'lib/ui';
import {constants as sharedConstants} from 'modules/shared';
import {selectors} from 'modules/current-user';

export const authenticatedRoute = connectedRouterRedirect({
  redirectPath: sharedConstants.PATHS.HOME,
  authenticatedSelector: state => !!selectors.selectUser(state).data,
  authenticatingSelector: state => selectors.selectUser(state).isRequesting,
  AuthenticatingComponent: Loader,
  wrapperDisplayName: 'AuthenticatedRoute',
});

```

When I remove `wrapper` from the `Route` component prop, everything works OK.

Much appreciate any help - I'm stuck on this one :)

**Comment by mjrussell** [comment]
What version of redux-auth-wrapper are you on? Can you show me the line from `npm ls`?

**Comment by marcdavi-es** [comment]
Sorry - `redux-auth-wrapper@2.0.2`

**Comment by mjrussell** [comment]
Thanks for the info, it does seem like you are hitting a place where its not ok to apply HOCs. Similar to some of the docs here - https://mjrussell.github.io/redux-auth-wrapper/docs/Getting-Started/Overview.html#where-to-apply

By applying the HOC inside the render (with a few layers of indirection) you can't get a stable identifier like you described. Its not really a problem with redux-auth-wrapper, I think you'd have this issue with any HOC.

There should be a way to get a factory approach working, but it is more challenging then applying the HOCs directly

**Comment by marcdavi-es** [comment]
@mjrussell Yep you're right - I wrote a dummy HOC and it got the same behaviour.

Nothing to do with your beaut library :)

Keep up the great work.
