### ISSUE TITLE
Trying to disable authenticatingSelector, "Uncaught Error: Maximum update depth exceeded."

### ISSUE THREAD

**Issue by johnunclesam** [mjrussell/redux-auth-wrapper#213]
Using this code: https://github.com/mjrussell/redux-auth-wrapper/blob/master/examples/react-router-4/auth.js

I need to disable at all the loadingComponent phase because I have a Global Loading Component. So I don't need it.

I just need to disable my Login Form Button.

But in that code if I comment this line:

```
const userIsAuthenticatedDefaults = {
  authenticatedSelector: state => state.user.data !== null,
  // authenticatingSelector: state => state.user.isLoading,
  wrapperDisplayName: "UserIsAuthenticated"
};
```

I get this error in console:

`Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

**How to disable the loading component phase?**

I just need only my login page.

**Comment by mjrussell** [comment]
That is how you disable the loading component. You must have some other issue/bug in your code. Can you post your full HOCs and your user reducer?

**Comment by johnunclesam** [comment]
Dear @mjrussell here there is the problem: https://codesandbox.io/s/j3llymyxqw

You can try with "/about" path which is "protected".

As you can see I commented out this line:

`// authenticatingSelector: state => state.user.isLoading,`

**Comment by johnunclesam** [comment]
I found that commenting also this part make the problem disappear. But absolutely there is something not clear at all, at least to me!

**before**:
```
const userIsNotAuthenticatedDefaults = {
  authenticatedSelector: state =>
    state.user.data === null && state.user.isLoading === false,
  wrapperDisplayName: "UserIsNotAuthenticated"
};
```

**after**:
```
const userIsNotAuthenticatedDefaults = {
  authenticatedSelector: state =>
    state.user.data === null, //&& state.user.isLoading === false,
  wrapperDisplayName: "UserIsNotAuthenticated"
};
```

**Comment by mjrussell** [comment]
The problem with the codepen you linked is that you created a state in which neither the wrapper could be true at the same time. By commenting out `authenticatingSelector: state => state.user.isLoading,`, this means that a user is **only** authenticated when `state.user.data !== null`. Anything else will redirect the user to `/login`. And then, we have the `userIsNotAuthenticated` which has `authenticatedSelector: state =>
    state.user.data === null && state.user.isLoading === false,`. So the user is "not authenticated" only when both `state.user.data === null` **and** `state.user.isLoading === false` are true. So if you reducer has a state of:
```js
data: null,
isLoading: true,
```
Neither auth-wrapper matches, causing infinite redirects between both routes. If you are using `isLoading` you need to create a scenario in which one of these is true for all cases. That's why my example has `authenticatingSelector: state => state.user.isLoading,`

For reference, this is the `auth.js` code you had:
```js
const userIsAuthenticatedDefaults = {
  authenticatedSelector: state => state.user.data !== null,
  // authenticatingSelector: state => state.user.isLoading,
  wrapperDisplayName: "UserIsAuthenticated"
};

export const userIsAuthenticated = connectedAuthWrapper(
  userIsAuthenticatedDefaults
);

export const userIsAuthenticatedRedir = connectedRouterRedirect({
  ...userIsAuthenticatedDefaults,
  // AuthenticatingComponent: Loading,
  redirectPath: "/login"
});

export const userIsAdminRedir = connectedRouterRedirect({
  redirectPath: "/",
  allowRedirectBack: false,
  authenticatedSelector: state =>
    state.user.data !== null && state.user.data.isAdmin,
  predicate: user => user.isAdmin,
  wrapperDisplayName: "UserIsAdmin"
});

const userIsNotAuthenticatedDefaults = {
  authenticatedSelector: state =>
    state.user.data === null && state.user.isLoading === false,
  wrapperDisplayName: "UserIsNotAuthenticated"
};

export const userIsNotAuthenticated = connectedAuthWrapper(
  userIsNotAuthenticatedDefaults
);

export const userIsNotAuthenticatedRedir = connectedRouterRedirect({
  ...userIsNotAuthenticatedDefaults,
  redirectPath: (state, ownProps) =>
    locationHelper.getRedirectQueryParam(ownProps) || "/",
  allowRedirectBack: false
});
```
