### ISSUE TITLE
React-Router-Redux and React-Router 2.0 with JWT example throw error on safari 9.0.3

### ISSUE THREAD

**Issue by wayann** [mjrussell/redux-auth-wrapper#22]
the example works on chrome but on Safari Version 9.0.3 (9537.86.4.4)

it complains about not finding a variable "fetch" am I missing something?

this what I get on my console
`ReferenceError: Can't find variable: fetch
(anonymous function)index.js:49
(anonymous function)index.js:8
(anonymous function)bindActionCreators.js:6
loginLoginView.js:20
login
login
dispatchEvent
invokeGuardedCallbackReactErrorUtils.js:70
executeDispatchEventPluginUtils.js:78
executeDispatchesInOrderEventPluginUtils.js:101
executeDispatchesAndReleaseEventPluginHub.js:42
executeDispatchesAndReleaseTopLevelEventPluginHub.js:53
forEach
forEachAccumulatedforEachAccumulated.js:22
processEventQueueEventPluginHub.js:258
runEventQueueInBatchReactEventEmitterMixin.js:17
handleTopLevelReactEventEmitterMixin.js:33
handleTopLevelWithoutPathReactEventListener.js:92
handleTopLevelImplReactEventListener.js:72
performTransaction.js:135
batchedUpdatesReactDefaultBatchingStrategy.js:61
batchedUpdatesReactUpdates.js:93
dispatchEventReactEventListener.js:203
(anonymous function)`

**Comment by mjrussell** [comment]
Thats interesting...looks like isomorphic fetch isn't working correctly on safari. Might be worth checking to see if that happens on the original repo - https://github.com/joshgeller/react-redux-jwt-auth-example. I dont regularly use safari but I can play around with it.

**Comment by wayann** [comment]
it happens also on the original repo

**Comment by wayann** [comment]
maybe instead of isomorphic fetch > https://github.com/github/fetch

**Comment by stroborobo** [comment]
It's just not imported, I created [a PR in the original repo](https://github.com/joshgeller/react-redux-jwt-auth-example/pull/18).

**Comment by mjrussell** [comment]
@stroborobo thanks good catch, I'll apply the same fix to the two branches on my fork

**Comment by mjrussell** [comment]
I've updated both of the branches on my fork
