### ISSUE TITLE
render AuthenticatingComponent component independently

### ISSUE THREAD

**Issue by mehrdaad** [mjrussell/redux-auth-wrapper#222]
The question I'm going to ask seems technically impossible for me, but I'm gonna ask anyway. 
I'm using React Router v4 alongside Redux Auth Wrapper.  
My routes files look something like this:  
```js
<MainTemplate>
    <Switch>
      <Route
        exact
        path="/"
        component={userIsAuthenticated(Threads)}
      />
    </Switch>
  </MainTemplate>
``` 
The point here is ``MainTemplate`` is a component witch renders its' ``children`` inside of itself.  
now, userIsAuthenticated is as follows:  
```js
function userIsAuthenticated(Component, allowRedirectBack = true) {
  return connectedRouterRedirect({
    redirectPath: '/auth/login',
    authenticatedSelector: (state) => {
      console.log('authenticated selector');
      if (state.auth.isAuthenticated) {
        return true;
      } else if (getToken()) {
        // try to refresh token
        return true;
      }
      return false;
    },
    authenticatingSelector: state => true,  //TODO: handle state via utilization of reducers and an state side effect management lib like redux-saga/redux-thunk
    AuthenticatingComponent: Loading, // TODO: render Loading component as the root component
    allowRedirectBack,
    wrapperDisplayName: 'UserIsNotAuthenticated',
  })(Component);
}
```
Before I continue, Let me clarify that what I'm trying to do is to invalidate JWT token asynchrosly,  
and while I do that I wanna show a ``Loading`` component there.  
Of course ``authenticatingSelector`` isn't implemented yet. And there should be the usage of reducers and sagas involved.  
The problem is: The ``Loading`` component renders inside ``MainTemplate`` because it lies within of ``MainTemplate``.  
I could have styled the component to imitate a standalone component but that's not my intention.
Is it somehow possible to render that ``Loading`` component independently without being infected by any other higher order component?  I mean the ``Loading`` component become the root component.
If not, any other insights to rearrange my codebase is more than welcome.

**Comment by mjrussell** [comment]
Hmm this is a bit tricky. I think if you really want to swap the `MainTemplate` for a `Loading` component you should put a custom HOC probably using [branch](https://github.com/acdlite/recompose/blob/master/docs/API.md#branch) from recompose. I think trying to fit it into your existing auth wrapper will be tricky and probably more complicated than you want.

**Comment by mehrdaad** [comment]
I'm overwhelm with how many react/redux libraries I should learn to create a SPA.
