### ISSUE TITLE
Component rerender for optional URI params

### ISSUE THREAD

**Issue by oldwin** [mjrussell/redux-auth-wrapper#234]
```JavaScript
        <Route
          exact
          path="/path/:id/:additional?"
          component={userIsAuth(MyComponent)}
        />
```
Will always fire Component lifecycle as componentWillMount() for location changes and rerender it again and again.

- /path/123
- /path/123/test <-- remount
- /path/123/test3 <-- remount

If I use just MyComponent without userIsAuth wrapper it works good without any remounting.

```JavaScript
        <Route
          exact
          path="/cottages/:id/:optional?"
          component={MyComponent}
        />
```

```JavaScript
const userIsAuth = connectedRouterRedirect({
  redirectPath: '/login',
  authenticatedSelector: ({ user }) => authenticatedSelector(user),
  wrapperDisplayName: 'UserIsAuthenticated',
  authenticatingSelector: ({ user }) => authenticatingSelector(user),
  AuthenticatingComponent: LoadingScreen,
  redirectQueryParamName: 'next',
});
```

Is it bug or any possibility to fix this behaviour?

**Comment by mjrussell** [comment]
I think this is the same as #227. Take a look at https://mjrussell.github.io/redux-auth-wrapper/docs/Getting-Started/Overview.html#where-to-apply. You may need to apply the HOC (i.e. `userIsAuth(MyComponent)`) outside the `Route` and pass it in

**Comment by oldwin** [comment]
@mjrussell thank you. Yes, it's the same issue like https://github.com/mjrussell/redux-auth-wrapper/issues/224

For now workaround from @dtweedle fixed the problem
https://github.com/mjrussell/redux-auth-wrapper/issues/224#issuecomment-375837028

```
const myComponentWrapped = userIsAuth(MyComponent);

<Route
  exact
  path="/path/:id/:additional?"
  component={myComponentWrapped}
/>
```
Will watch another issue.
