### ISSUE TITLE
Example with react 16.x

### ISSUE THREAD

**Issue by djaax** [mjrussell/redux-auth-wrapper#242]
I encountered an issue with the example for react-router-4 in react 16.4.0 at /examples/react-router-4/App.js.

I found the solution declaring the HOCs inside the Class Component, as such:

```
...
class App extends Component {
    // Need to apply the hocs here to avoid applying them inside the render method
    const Login = userIsNotAuthenticatedRedir(LoginComponent)
    const Protected = userIsAuthenticatedRedir(ProtectedComponent)
    const Admin = userIsAuthenticatedRedir(userIsAdminRedir(AdminComponent))

    render() { ... }
}
...
```

Maybe this helps someone.

**Comment by nate-whil** [comment]
I didn't need to declare them inside the class component but this bit helped `const Admin = userIsAuthenticatedRedir(userIsAdminRedir(AdminComponent))`

**Comment by mjrussell** [comment]
Its never a bad idea to apply the hocs outside of the render method, however I've got my example with react-router-4 working with the latest react. Im going to close this
