### ISSUE TITLE
React Native branch?

### ISSUE THREAD

**Issue by klatchbaldar** [mjrussell/redux-auth-wrapper#25]
Would it be possible to create a branch that implements this for React Native?

**Comment by mjrussell** [comment]
@klatchbaldar im not sure exactly what would be required for React Native support. Do you have thoughts on what that requirement would be?

**Comment by klatchbaldar** [comment]
I'll see if I can help put something together...

**Comment by mjrussell** [comment]
@klatchbaldar see #33. I'll get a release out shortly

**Comment by mjrussell** [comment]
Version 0.4.0 is out on npm now
