### ISSUE TITLE
Doesn't work with latest react

### ISSUE THREAD

**Issue by AuthorProxy** [mjrussell/redux-auth-wrapper#253]
"connected-react-router": "^6.6.1",
"react": "^16.11.0",
"react-dom": "^16.11.0",
"connected-react-router": "^6.6.1",

**Comment by mjrussell** [comment]
What exactly doesn't work?

**Comment by mjrussell** [comment]
[3.0.0](https://github.com/mjrussell/redux-auth-wrapper/releases/tag/3.0.0) should work with that setup

**Comment by AuthorProxy** [comment]
no still not, it doesn't redirect after successful login\unlogin

temporary fix is add `forwardRef: true`
![image](https://user-images.githubusercontent.com/1407631/72515427-ed736500-3860-11ea-92d4-d837ce17dfaf.png)

but this add new problem that hot-reload doesn't work at version > "@hot-loader/react-dom": "^16.8.6", it goes to unlimited outbound error
`React-Hot-Loader: some components were updated out-of-bound. Updating your app to reconcile the changes.`

but anyway it's better solution now, than not updating libs at all, at some time everything was worked until packages were updated (react, babel, webpack, etc...). Now everything work with latest versions (except react-hot-loader, which I leave at 16.8.6 at current moment), but in future if bug doesn't dissapear, I should stop this lib, because I cannot fix it someself.

We can connect and I can give you temp access via anytime\teamviewer to my laptop, if you want to check it
