### ISSUE TITLE
Reference Error: Unknown Plugin

### ISSUE THREAD

**Issue by Connorelsea** [mjrussell/redux-auth-wrapper#26]
I am getting an error when running `npm run start` in examples/basic. I have run `npm install` in this directory previously.

![img_2016-03-07 10 48 29](https://cloud.githubusercontent.com/assets/1844458/13576224/48559efa-e452-11e5-8218-a21a0c7a22bc.jpg)

**Comment by mjrussell** [comment]
Hmm it looks like the basic example is picking up the `.babelrc` from the directory above despite it having its own in the folder. If you run `npm install` in the root folder does the example start working? The root `package.json` includes the decorator transform

**Comment by Connorelsea** [comment]
Running `npm install` in the root directory fixed the issues. Thank you. Now to get to trying to wrap my head around the example!

**Comment by mjrussell** [comment]
Thanks, good to know. I'll probably update the README examples to npm install the root first.

**Comment by Connorelsea** [comment]
Also, can I ask a quick question? Where exactly should I look into putting my own logic for talking to the server for user information? What's confusing me the most is a general idea of how to handle the userUpdate reducer but with server information. Any kind of tips or suggestions would probably help a ton.

**Comment by mjrussell** [comment]
@Connorelsea good question. This library tries to be extremely flexible in terms of allowing whatever method for communicating with your server or using JWT/cookies, etc. So theres not a ton of guidance there, and you can only see some ideas in the examples which communicate with a server.

Here's a pretty easy workflow, let me know if you have further questions:

A lot of it comes down to how you want to best structure your app, but I think for getting started, the simplest thing is to use a api middleware (maybe like https://github.com/agraboso/redux-api-middleware) or follow the examples in the redux real-world example (https://github.com/reactjs/redux/blob/master/examples/real-world/middleware/api.js) and then in your actions file like `authActions.js` or something. Include a `login`, `logout`, and `fetchUser` call. 

You want to dispatch the `fetchUser` on app load to see if there is an existing cookie, and use the response of that call (with the response data containing some basic user info) to populate the `userUpdate` reducer. If that call fails, the auth-wrapper will simply redirect them to the login page and you can chain the `login` action call to also dispatch `fetchUser` onSuccess.

**Comment by Connorelsea** [comment]
I will work through these ideas and attempt to build on top of the example you have provided. Do you suggest the api middleware you linked over something like redux-thunk or redux-saga which I see talked about far more often?

**Comment by mjrussell** [comment]
The API one is nice because its fairly rigid, you can still use some of that if you want in combo with thunk or sagas. I use both heavily, but have been trying to rewrite more thunks to sagas lately. 

I would say that just a simple thunk based approach will be painful in your action creators (just lots of callbacks), you will definitely want an "api middleware" if you go that approach to abstract all the common response handling. Redux-promise with a promise based ajax will work too. Lots of options :smile:

Sagas are definitely the new kid on the block, and are a lot of fun but you might want to limit the learning curve in the beginning.

**Comment by Connorelsea** [comment]
I've done most of the abstract React/Redux tutorials out there and have learned the basics, so this is my first time trying to build something "whole" and my first encounter with any of those three options, so I don't even really know the difference. The decisions paralysis has been overwhelming, so I think I'll just blindly attempt to build something with the API middleware and see how it goes from there. I originally thought the saga and thunk libraries were for interacting with APIs and server data, but I guess there's a bigger difference. I will go the route of what you suggested and report back if I encounter any issues. I appreciate your explanations.

**Comment by mjrussell** [comment]
Im going to close this issue since there hasn't been any recent activity and its not really acitonable. Feel free to re-open if you wan to continue the discussion
