### ISSUE TITLE
Type {} is missing the following properties from type Readonly<InjectedAuthProps>

### ISSUE THREAD

**Issue by ligowsky** [mjrussell/redux-auth-wrapper#260]
When I use redux-auth-wrapper with TypeScript, for example:

```
const EditorLink = visibleOnlyForAdministator(() => (
  <NavLink className="nav-link" to="/editor">
    Editor
  </NavLink>
));
```

I get an error: 
_Type '{}' is missing the following properties from type 'Readonly<InjectedAuthProps>': isAuthenticated, isAuthenticating ts(2739)_

As I understood, those props are defined as required and TypeScript asks me to pass isAuthenticated and isAuthenticating props to the component Editor, like this: 
`<EditorLink isAuthenticated={false} isAuthenticating={false} />`
But isn't it redux-auth-wrapper's job to take care on passing down props? What should I do to avoid this error?

**Comment by SmolinPavel** [comment]
@ligowsky looks like I'm having the same issue. Did you manage to resolve this one?
