### ISSUE TITLE
Versioning Order

### ISSUE THREAD

**Issue by arbrog** [mjrussell/redux-auth-wrapper#285]
The newest released version is [v1.1.1](https://github.com/mjrussell/redux-auth-wrapper/releases/tag/v1.1.1) but the release before that one was was [3.0.0](https://github.com/mjrussell/redux-auth-wrapper/releases/tag/3.0.0). Are the major version three parallel releases which are all active or is the major version number just being reset back to 1?

**Comment by mjrussell** [comment]
v1.1.1 was released in response to #278. I'd like to only support 3.x going forward (and minimally, I'm not doing much in terms of updates to this library), but someone did all the work to fix something that was an issue on 1.x so I wanted to release a bugfix version for it.

Please continue to use 3.0.0 and if there are updates to it i'll release minior/bug versions

**Comment by arbrog** [comment]
Understood. One thing to note is it looked like v1.1.1 is marked as latest from a package install version. This broke things when I `yarn add redux-auth-wrapper` I'm guessing this isn't intentional if 3.x is the main version?

```
yarn info v1.22.5
{
  name: 'redux-auth-wrapper',
  description: 'A utility library for handling authentication and authorization for redux and react-router',
  'dist-tags': {
    latest: '1.1.1'
  },
  ...
  ```

**Comment by mjrussell** [comment]
Ah hm..thanks. I'll need to see how to fix that

**Comment by mjrussell** [comment]
Thanks, now I know about `dist-tags` 😄  Should be all set:
```
yarn info redux-auth-wrapper
yarn info v1.21.1
{ name: 'redux-auth-wrapper',
  description: 'A utility library for handling authentication and authorization for redux and react-router',
  'dist-tags': 
   { latest: '3.0.0' },
  versions: 
...
```
