### ISSUE TITLE
Duplicated `authData` in store.

### ISSUE THREAD

**Issue by sunglee** [mjrussell/redux-auth-wrapper#29]
Hi,

I have `auth` and `data` reducer and I followed tutorial to use `UserAuthWrapper`. It works ok, but when I see store, I see `authData` which is exactly same copy of `auth` in dev tool. I tried `React-Router-Redux and React-Router 2.0 with JWT` sample and it doesn't show `authData` in store. What am I missing? Is it caused by the store configuration? Thanks for your help.

**Comment by mjrussell** [comment]
@sunglee the `UserAuthWrapper` doesn't add any additional reducers to your store, it just gets passed a selector of the store to know how to access the "authentication data" inside your component.

In the docs, the term `authData` is the value that is returned after applying the `authSelector` to the store, i.e. `const authData = authSelector(store)`. This is just a name used for the docs and for convenience in the examples

**Comment by mjrussell** [comment]
Going to close, but feel free to re-open if you don't understand my response
