### ISSUE TITLE
User loaded asyncroniously in browser

### ISSUE THREAD

**Issue by apedyashev** [mjrussell/redux-auth-wrapper#30]
My application works with 3rd party API only  so I'm going to serve files statically (and I.m unable to initialize the store on the server). 
Because of that my app is always redirected to /login before user is loaded and added to the store.

It would be nice to have example or recommendations how to handle this case.

I have following workaround, but I don't like it:

```
const UserIsAuthenticated = UserAuthWrapper({
  authSelector: state => {
    return {
      wasRequested: state.isLoggedUserRequested,
      data: state.entities.loggedUser
    };
  },
  redirectAction: (path) => replaceState(null, path.pathname, path.query),
  wrapperDisplayName: 'UserIsAuthenticated',
  allowRedirectBack: false,
  predicate: user => {
    // logged user has not been requested yet - redirect to /login page is not required
    if (!user.wasRequested) {
      return true;
    }
    // user has been requested but user is not logged - redirect to /signin
    else if (user.wasRequested && isEmpty(user.data)) {
      return false;
    }

    return true;
  }
});
```

`isLoggedUserRequested` is set to true when request to /users/me has been completed.

**Comment by mjrussell** [comment]
@apedyashev thanks for the issue. I think its somewhat related to the discussions in https://github.com/mjrussell/redux-auth-wrapper/issues/10#issue-127519739. I think one solution would be to have an `isAuthenticating`/`isLoggingIn` selector and an optional component to display while this is true. If false, the normal auth flow kicks in.

Do you think that would solve this use case?
