### ISSUE TITLE
Cannot resolve module 'babel'

### ISSUE THREAD

**Issue by johnwiseheart** [mjrussell/redux-auth-wrapper#36]
Hi there,
I'm trying to run the example, and facing this issue, which I can't seem to solve. It would appear to me to be an issue when trying to run babel on the root src directory - but this is after doing an `npm install` there too.

```
ERROR in /Users/John/projects/redux-auth-wrapper/src/index.js
Module not found: Error: Cannot resolve module 'babel' in /Users/John/projects/redux-auth-wrapper/src
 @ /Users/John/projects/redux-auth-wrapper/src/index.js 12:15-35
```

**Comment by mjrussell** [comment]
Hmm looks like the examples got busted after the React Native support. Thanks for reporting, will work on this now

**Comment by mjrussell** [comment]
@johnwiseheart should be all set if you pull from master. Looked like it was trying to resolve the babel-loader from the root directory when trying to use the resolve-alias
