### ISSUE TITLE
Handling two different user roles

### ISSUE THREAD

**Issue by omago** [mjrussell/redux-auth-wrapper#41]
Hi everyone,

I have a question, i ma not sure which is the correct approach. 

I have two roles "admin", "user". Both of them have dashboards that i want to show on "/" route. When admin is logged in he can see his version of dashboard and when user is logged in he can see his version of dashboard. Both dashboards should be display on "/" route. 

If i do something like this:

`<Route path="/" component={UserIsAuthenticated(UserIsAdmin(AdvertiserLayout))}>
</Route>`
`<Route path="/" component={UserIsAuthenticated(UserIsAdvertiser(AdvertiserLayout))}>
</Route>`

This is not working properly, it works ok if i login as Admin, but if i login as user i am redirected to login because UserIsAdmin condition is not matched.

Should i change my approach, is there any other way?

**Comment by mjrussell** [comment]
@omago thats an interesting use case and the auth wrapper in its current form probably does not solve this easily. The routes will always match first and you cant change the routes based on the store in React Router, so listing them sequentially wont work in this case.

One option you could do is use the auth wrapper for the `/` route as just the authentication, not authorization.

So you'd have a route like:
`<Route path="/" component={UserIsAuthenticated(AdvertiserLayout)} />`

Then inside the Advertiser layout, you have the `authData` as a prop and can do something like the following in your render:
```js

render() {
  if (this.props.authData.isAdmin) {
    return <AdminAdvertiserLayout />;
  } else {
    return <AdvertiserLayout />;
  }
}
```

**Comment by omago** [comment]
Hi Matthew, 

Thanks for your reply, i will try your approach. The best would be to implement authentication and autorization so they are independent. That way it could be possible that if non of the routes match users role they can have some kind of "Not allowed" page. Once again, thanks for your answer.

**Comment by mjrussell** [comment]
@omago if you have any suggestions or improvements to the library that you think would make this easier definitely let me know! In my apps I typically route admins/users to different locations rather than displaying different data on the same route. 

You could also write your own HOC that behaves similar to and takes in two different components and decides with an auth check on which to render.
