### ISSUE TITLE
Redirecting Already authorized users to a specific route

### ISSUE THREAD

**Issue by storrdev** [mjrussell/redux-auth-wrapper#43]
I've been looking over the docs for a while now and I'm unable to come up with a way to do this. I'm not sure if it's possible currently, or if this might be an enhancement request.

What I would like to do is redirect users who are already authorized when they try to access certain routes (i.e. /login or /signup). I would redirect the users to the route that they recieve after loggin in successfully (in my app it's currently /dashboard).

It's basically like the failureRedirect option arg except more like 'authenticatedRedirect'  or something.

Your package has been a great help so far!

**Comment by mjrussell** [comment]
@storrdev Glad its been helpful! You are right the auth wrapper doesn't currently have a wrapper for redirecting users who are already authenticated. I've been meaning to write another HOC that does this automatically (#2), maybe using an existing wrapper or just being its own HOC.

Both examples have the code for how to do it though, see https://github.com/mjrussell/redux-auth-wrapper/blob/master/examples/basic/components/Login.js#L31-L37.

Essentially you want to connect your Login component and then check the auth selector. If its true, meaning the use is already logged in, then inspect the redirect parameter (if you want to support sending users to deep link routes after logging in successfully). Then you write a small function like the following in your Login Component:

```js
    ensureNotLoggedIn = (props) => {
      const { isAuthenticated, replace, redirect } = props

      if (isAuthenticated) {
        replace(redirect)
      }
    };
```

And hook it into your willMount/willReceiveProps.

**Comment by storrdev** [comment]
Thanks for pointing that example out! I'm sure I skimmed over that example but missed exactly what was going on. This has solved my issues.
