### ISSUE TITLE
Not redirecting to /login properly

### ISSUE THREAD

**Issue by emzero** [mjrussell/redux-auth-wrapper#48]
I'm trying to use your library with no luck whatsoever.

The condition seems to be working because if I set `authSelector: state => state` it goes through the protected route with no problem.
But when I use the proper authSelector I end up in the protected route but with a blank page.

Bootstrap:
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { browserHistory, Router } from 'react-router';
import { syncHistoryWithStore } from 'react-router-redux';
import configureStore from './configureStore';
import routes from './routes';

// Get the application-wide store instance, prepopulating with state from the server where available.
const initialState = window.initialReduxState;
const store = configureStore(initialState);
const history = syncHistoryWithStore(browserHistory, store);

// This code starts up the React app when it runs in a browser. It sets up the routing configuration
// and injects the app into a DOM element.
ReactDOM.render(
  <Provider store={ store }>
    <Router history={ history } children={ routes } />
  </Provider>,
  document.getElementById('react-app')
);
```

Routes (imported and added as children to the parent Router:
```jsx
  <Route>
    <Route path='/login' onEnter={ redirectToYammerAuth } />
    <Route path='/stream' component={ UserIsAuthenticated(Stream) } />
    <Route path='/yammer/callback' component={ YammerCallback } />

    <Route component={Layout}>
      <Route path='/' components={{ body: Home }} />
      <Route path='/counter' components={{ body: Counter }} />
      <Route path='/fetchdata' components={{ body: FetchData }}>
        <Route path=':startDateIndex' /> { /* Optional route segment that does not affect NavMenu highlighting */ }
      </Route>
    </Route>
  </Route>;
```

AuthWrapper:
```jsx
const UserIsAuthenticated = UserAuthWrapper({
  authSelector: state => state.currentUser.id, // how to get the user state
  redirectAction: push,
  wrapperDisplayName: 'UserIsAuthenticated' // a nice name for this auth check
});
```

So when `state.currentUser.id` is falsy it should redirect to `/login`. As I said, it seems to properly understand that it should redirect but it's not working.
The following action is triggered:
![image](https://cloud.githubusercontent.com/assets/412489/16144177/ab753c58-3447-11e6-85cf-b58ee1a9d74a.png)

And this is what the component hierarchy looks like:
![image](https://cloud.githubusercontent.com/assets/412489/16144224/efb2c020-3447-11e6-8948-8b1acf0720f9.png)

If it helps, I've cloned [this repo](https://github.com/xabikos/aspnetcore-react-redux-template) and I haven't changed anything besides adding a few components and the auth/routes logic.

**Comment by mjrussell** [comment]
@emzero if you are using `react-router-redux` to dispatch actions you need to [apply the routingMiddleware to your store](https://github.com/reactjs/react-router-redux#what-if-i-want-to-issue-navigation-events-via-redux-actions). Otherwise dispatching the replace won't trigger a history location change. Here's the relevant code from the README (note the `createStore` call):

```js
import { routerReducer, syncHistoryWithStore, routerActions, routerMiddleware } from 'react-router-redux'
import { UserAuthWrapper } from 'redux-auth-wrapper'
import userReducer from '<project-path>/reducers/userReducer'

const reducer = combineReducers({
  routing: routerReducer,
  user: userReducer
})
const baseHistory = createHistory()
const routingMiddleware = routerMiddleware(baseHistory)

// Note: passing middleware as the last argument requires redux@>=3.1.0
const store = createStore(
  reducer,
  applyMiddleware(routingMiddleware)
)
const history = syncHistoryWithStore(baseHistory, store)
```

**Comment by emzero** [comment]
I added the routingMiddleware and it's properly redirecting to /login but now I'm having a loop between my callback and login routes.

I see this error popups in the console:
`warning.js:44 Warning: Failed propType: Invalid prop `authData` of type `number` supplied to `UserIsAuthenticated(Connect(Stream))`, expected `object`. Check the render method of `Connect(UserIsAuthenticated(Connect(Stream)))`.`

**Comment by emzero** [comment]
Continues on https://github.com/mjrussell/redux-auth-wrapper/issues/46
