### ISSUE TITLE
an integration issue with redux-router and  server rendering.

### ISSUE THREAD

**Issue by Ieremchuk** [mjrussell/redux-auth-wrapper#52]
according to the documentation I need to use the workaround for server rendering 
That requires passing a redux store into the connect wrapper.

```javascript
const getRoutes = (store) => {
  const connect = (fn) => (nextState, replaceState) => fn(store, nextState, replaceState);
return (
    <Route>
      <Route path="/" component={App}>
        <Route path="login" component={Login}/>
        <Route path="foo"
           component={UserIsAuthenticated(Foo)}
           onEnter={connect(UserIsAuthenticated.onEnter)} 
         />
      </Route>
    </Route>
  );
};
```
From another side the redux-router middleware demands routes to be created first.

```javascript

// Compose reduxReactRouter with other store enhancers
const store = compose(
  applyMiddleware(m1, m2, m3),
  reduxReactRouter({
    routes,
    createHistory
  }),
  devTools()
)(createStore)(reducer);
```
I cannot create store without routs and routs without store.
Is any workaround available?

**Comment by Ieremchuk** [comment]
@mjrussell Thanks for your answer. Could you please add a little bit more about "hoisting" approach( any google keys or link to documentation )? I am not an experienced js developer.

Regarding the easier approach. I saw this example. It contains a server part as well ([link](https://github.com/acdlite/redux-router/blob/master/examples/server-rendering/server.js)) .
And this part is a main problem for me, because it uses the routes. 

```javascript
app.use((req, res) => {
  const store = reduxReactRouter({ routes, createHistory: createMemoryHistory })(createStore)(reducer);
  const query = qs.stringify(req.query);
  const url = req.path + (query.length ? '?' + query : '');
// skiped
```

**Comment by mjrussell** [comment]
@Ieremchuk sorry for not looking through the example more thoroughly...the trick with this approach is "abusing" how the references work in javascript. Instead of capturing scoped variables in a closure, references always refer back to the variables. For example:

```js
let x;
function y() {
  return x + 1;
}
y() // returns NAN
x = 1;
y() // returns 2
```

So in your case you could do something like:
```js
let store;
const routes = createRoutes(store); 
store = reduxReactRouter({ routes, createHistory: createMemoryHistory })(createStore)(reducer);
```

The connectRedirect only needs the store when the `onEnter` fires, which is long after the store has been created.

**Comment by Ieremchuk** [comment]
@mjrussell It doesn't work for me. By some reason the store remains undefined inside the connect.

```javascript
const getRoutes = (store) => {
  console.log(store); // undefined
  let connect = function connect(fn) {
    return function (nextState, replaceState) {
      console.log(store); // still left undefined when the top level store has been already created
      return fn(store, nextState, replaceState);
    };
  };

```
Looks like something wrong with closer. I will try to figure out.
Thanks for your efforts and time.

**Comment by Ieremchuk** [comment]
@mjrussell Solution that works for me.

1) move connect outside the getRouts.
```javascript
const getRoutes = (connect) => {
return (
    <Route>
      <Route path="/" component={App}>
        <Route path="login" component={Login}/>
        <Route path="foo"
           component={UserIsAuthenticated(Foo)}
           onEnter={connect(UserIsAuthenticated.onEnter)} 
         />
      </Route>
    </Route>
  );
};
```
2) And define connect in global context that allows to capture the store in closure.

```javascript
let store;
const connect = (fn) => (nextState, replaceState) => fn(store, nextState, replaceState);
const routes = createRoutes(connect); 
store = reduxReactRouter({ routes, createHistory: createMemoryHistory })(createStore)(reducer);
```
All works as expected.
