### ISSUE TITLE
Wrap HOC around a bunch of routes rather than a specific component

### ISSUE THREAD

**Issue by gCardinal** [mjrussell/redux-auth-wrapper#53]
What I mean is something like this:

```
export default () => {
	return (
		<Route path='/' component={BaseLayout}>
			<IndexRedirect to="/login" />
			<Route path='login' component={LoginView} />
			<UserIsAuthenticated>
				<Route path="conversations" component={ConversationsView } />
				<Route path='*' component={ErrorView} />
			</UserIsAuthenticated>
		</Route>
	)
}
```

I realize I could simply wrap every single component like so `UserIsAuthenticated(Foo)`, but I'm wondering if there wouldn't be a cleaner way to prevent a bunch of routes from being accessed by a logged out user.

For the record, the above code sample wouldn't work for me. I'm pretty sure it's normal though. Is that something we'd want to be able to do?

**Comment by mjrussell** [comment]
That's an interesting idea, you can currently do something similar if you have a route that sits at the level you want to authenticate. You aren't required to have path properties for the Routes. So you can create a component that just returns the children passed to it from React Router and renders it. Something like:
```js
const Authenticated = UserIsAuthenticated((props) => props.children);

export default () => {
    return (
        <Route path='/' component={BaseLayout}>
            <IndexRedirect to="/login" />
            <Route path='login' component={LoginView} />
            <Route component={Authenticated}>
                <Route path="conversations" component={ConversationsView } />
                <Route path='*' component={ErrorView} />
            </Route>
        </Route>
    )
}
```

I suppose it would be easy to export a helper for such things so you could have the syntax in your example. 

The only thing I could think of is that if the children of the protected route use `getComponents` and to return multiple components then this approach would not work.

**Comment by gCardinal** [comment]
Thank you for your answer, I actually didn't know Routes didn't need a path to work! Your solution is exactly what I was looking for!

**Comment by mjrussell** [comment]
Glad this worked for you. I'll add something to the README so others can find this more easily

**Comment by toobulkeh** [comment]
```
const Authenticated = UserIsAuthenticated((props) => props.children);
```

Works for me, while the current documentation method:
```
const Authenticated = UserIsAuthenticated((props) => React.cloneElement(props.children, props));
```

Renders the components twice.

Hope this helps.

**Comment by mjrussell** [comment]
@toobulkeh could it be that your child component also has a child property you are rendering if present? The reason for the clone is to preserve props passed down from above which `props.children` would not.

Maybe something like this would handle that edge case?
```js
const Authenticated = UserIsAuthenticated(({ children, ...props }) => 
  React.cloneElement(children, props));
```

**Comment by toobulkeh** [comment]
For more context, here's what we're doing:

```jsx
// routes/App.js
import React, { Component } from 'react'

import Navbar from '../components/App/Navbar'
import Footer from '../components/App/Footer'

export default class AppRoute extends Component {
  static propTypes = {
    children: React.PropTypes.object.isRequired
  }

  render() {
    return (
      <div>
        <Navbar />
        {this.props.children}
        <Footer />
      </div>
    )
  }
}
```

```jsx
//index.js

const Authenticated = AssociateIsAuthenticated((props) => props.children);

ReactDOM.render(
  <Provider store={store}>
    <Router history={history} render={applyRouterMiddleware(useScroll())}>
      <Route path='/' component={RootRoute} >
        <Route component={Authenticated}>
          <Route path='app' component={AppRoute}>
            <IndexRedirect to='/app/profile' />
            // ...
          </Route>
        </Route>
        // ...
)
```
