### ISSUE TITLE
Using internationalized URLs

### ISSUE THREAD

**Issue by reintroducing** [mjrussell/redux-auth-wrapper#54]
Hello and thank you for this component.  I've tried to look over the docs but I'm not exactly sure how to accomplish what I'm doing.  My URLs are internationalized (`/en-us/dashboard` for instance) and I'm having trouble getting the login redirect working.  Here is my setup:

Main file with Router:
```
render((
    <Provider store={store}>
        <Router history={history}>
            <Redirect from="/" to={`/${getCurrentLanguage().lcid}/dashboard`} />
            {routes}
        </Router>
    </Provider>
), document.getElementById('root'));
```

Routes file:
```
// On first load make sure that the language in the URL is the same as the
// current language and if not then set it and update the messages in the store.
const ensureLanguageMatch = (nextState, replace, cb) => {
    const lcidFromUrl = nextState.params.lcid;

    if (lcidFromUrl !== getCurrentLanguage().lcid) {
        setCurrentLanguage(getLocale(lcidFromUrl), false);

        store.dispatch(update({
            locale: getCurrentLanguage().locale,
            messages: TRANSLATIONS[getCurrentLanguage().lcid]
        }));
    }

    cb();
};

const UserIsAuthenticated = UserAuthWrapper({
    authSelector: state => {
        return state.user;
    },
    redirectAction: routerActions.replace,
    wrapperDisplayName: 'UserIsAuthenticated'
});

export default (
    <Route path="/" onEnter={ensureLanguageMatch}>
        <Route path=":lcid" component={App}>
            <IndexRoute component={UserIsAuthenticated(DashboardContainer)} />
            <Route path="login" component={UserLogin} />
            <Route path="dashboard" component={UserIsAuthenticated(DashboardContainer)} />
            <Route path="messages" component={UserIsAuthenticated(MessagesContainer)}>
                <IndexRoute component={ConversationsSectionContainer} />
                <Route path=":conversationId" component={MessagesSectionContainer} />
            </Route>
            <Route path="goals" component={Goals} />
            <Route path="learning" component={Learning} />
            <Route path="community" component={Community} />
            <Route path="help" component={Help} />
            <Route path="ui" component={UIKit} />
        </Route>
    </Route>
);
```

Result of this is that upon page load the user gets redirected to `http://localhost:3000/en-us/dashboard` but nothing displays (not even my original dashboard component) but the header and footer (which are in App).

By removing the `redirectAction` in UserIsAuthenticated the user gets redirected to `http://localhost:3000/login?redirect=%2Flogin%3Fredirect%3D%252Fen-us%252Fdashboard` and again nothing is shown except for the header and footer from App.

I know this is a pretty specific use case but I'd really appreciate if you could help me out in understanding what I'm doing incorrectly and how to alleviate this.

**Comment by reintroducing** [comment]
Disregard, just realized what `failureRedirectPath` is. *facepalm*

**Comment by mjrussell** [comment]
@reintroducing glad you found it! Let me know if I need to make the documentation on it any more clear

**Comment by reintroducing** [comment]
This was totally my error, for some reason when I first read it I thought "redirect on login error" as opposed to redirect when auth says you're not logged in. It wasn't until I ran into my issue and reread it closer that I realized it was defaulted to /login and that was exactly what I wanted to alter.
