### ISSUE TITLE
Logging out without setting redirect param (whilst allowRedirectBack: true)

### ISSUE THREAD

**Issue by robinpyon** [mjrussell/redux-auth-wrapper#59]
Firstly, thanks for the great library. It's been a massive help.

Hopefully I haven't missed anything obvious in the docs. Thanks!

—

Looking at the [basic example](https://github.com/mjrussell/redux-auth-wrapper/tree/master/examples/basic) provided in this repo (where `/foo` is protected)

- Is it possible to log out and NOT append the redirect query  
e.g. `/foo` -> (user presses logout) -> `/login`
- ... whilst also ensuring direct links to protected pages by unauthenticated users redirect accordingly?  
e.g. Unauthenticated user visits `/foo` -> (UserAuthWrapper checks authSelector) -> `/login?redirect=%2Ffoo`

**Comment by mjrussell** [comment]
Glad its been helpful!

Could you explain a little more how you will determine if the user has not yet authenticated or if they have clicked the logout button? Currently there isn't any want to distinguish between the two. One option is to let `allowRedirectBack` be either a bool or a function of `state -> bool` provided you have some flag in your state that is set if the user has logged in previously.

Another alternative that doesn't require a change to the library would be to define a route for `/logout` that has an onEnter method (or a component with a willMount) that dispatches an action to clear the user data and then redirect the user the `/login`. This route wouldn't be protected by the auth wrapper.

Open to other suggestions as well if you have an idea

**Comment by robinpyon** [comment]
I'm an idiot. In the basic example, calling `replace('/')` right after logout does just this! Having a separate unprotected logout route isn't necessary.

—

However, the specific issue that I was having leading to this question was that I had an async action (unsubscribe) that needed to also log out the user upon success.

I resolved this by not having the unsubscribe action touch any log in state, instead listening to the outcome of unsubscribe in my component and then dispatching a separate logout action (whilst also replacing the URL)

Your suggestion to `allowRedirectBack` sounds good though! I just wonder if it'd see enough usage to warrant a change?

**Comment by mjrussell** [comment]
Glad you got it working, there are always a ton of different ways to approach these type of routing challenges. I'll wait and see if theres desire for the `allowRedirectBack` enchancement
