### ISSUE TITLE
After successful login app does not automatically redirect

### ISSUE THREAD

**Issue by sublimeye** [mjrussell/redux-auth-wrapper#62]
I've been struggling with this for last several hours.

1. I have a "protected" route
2. When I goto, wrapper redirects me to the /login page with redirect=users
3. When I successfully logs in user object is get populated with data
4. But wrapper does not redirect to 'users' page

- neither render nor componentWillReceiveProps get executed when user logs in. It seems like the wrapper does receive any updates when application state changes.
- If I press 'users' link in the app after login wrapper does not restrict access anymore

Please help me with some ideas... My head is blowing out with redux and actions/state updates propagation :'(

**Comment by mjrussell** [comment]
@sublimeye The HOC only wraps the protected route, forcing out users who aren't authenticated. It does not affect your Login component nor get notified after login has succeeded. You need to add some logic to your Login component (via HOC or directly) to send the user back to the page they were trying to get to.

I haven't yet created an easy to import HOC (see #2). See the Login component in the [basic example](https://github.com/mjrussell/redux-auth-wrapper/blob/master/examples/basic/components/Login.js)

**Comment by sublimeye** [comment]
@mjrussell OhMY..... I though `redirect` param was used exactly for this purpose and was trying  understand why it's not working >___<

When I looked in `componentWillReceiveProps` and saw `createRedirect` I though it will do the job. Although now I realize that componentWillReceiveProps wouldn't get fired unless Router will trigger route change ... which is definitely not a "ON_LOGIN_SUCCESS" handler.... 

Thanks anyways, I kind of started loosing my mind trying to make it work 👍

**Comment by mjrussell** [comment]
You aren't the first person to get confused about whats necessary to do in the Login Component. I think that Im going to make the docs more clear and finally write that login HOC I've been meaning to and include that in the documentation.

**Comment by navmalc** [comment]
Is there a way of making this note a sticky? I was looking through as I've been wondering the same thing!

**Comment by oyeanuj** [comment]
+1 for the Login HOC and/or docs or example gists!

**Comment by mjrussell** [comment]
I added a gist of how to do a Login Higher Order Component in  https://github.com/mjrussell/redux-auth-wrapper/issues/2 and I updated the loading example [here](https://github.com/mjrussell/redux-auth-wrapper/tree/master/examples/loading) to use it

**Comment by mjrussell** [comment]
I also just added a note about it to the Tutorial in the readme in https://github.com/mjrussell/redux-auth-wrapper/commit/e4f208fb7d916d2510761bee3f12d01d56f73f6c
