### ISSUE TITLE
Example of displaying a snackbar / toast / notification on redirect?

### ISSUE THREAD

**Issue by ernie-eunsang** [mjrussell/redux-auth-wrapper#64]
Instead of redirecting to a route where a user can authenticate (like `/login`), I'd like to redirect the user and show some messages. An example from [README](https://github.com/mjrussell/redux-auth-wrapper#authorization--more-advanced-usage):
```js
// Regular authentication & redirect to login from before
const UserIsAuthenticated = UserAuthWrapper({ ... })

// Admin Authorization, redirects non-admins to /app
const UserIsAdmin = UserAuthWrapper({
  failureRedirectPath: '/app',
  predicate: user => user.isAdmin,
  ...
})

<Route path="foo" component={UserIsAuthenticated(UserIsAdmin(Admin))}/>
```
I really think the user would like to know why he/she is redirected to `/app`. So I have a custom snackbar(toast, notification, or however you call [the component that displays a breif feedback](https://material.google.com/components/snackbars-toasts.html)) integrated with redux state. I am trying to wrap my head around this, but not sure how to capture redirection event and dispatch an action accordingly. Any ideas?

The way I currently set up the snackbar is this:

```js
// actions.js
const ADD_SNACKBARS = 'ADD_SNACKBARS';
const DELETE_SNACKBARS = 'DELETE_SNACKBARS';

export const addSnackbars = ({ type, text }) => ({ ... });
export const deleteSnackbars = (id) => ({ ... });

// reducer.js
export default (state = {}, { type, payload }) => {
  switch (type) {
    case ADD_SNACKBARS:
      return { ... };
    case DELETE_SNACKBARS:
      return { ... };
    default:
      return state;
  }
};

// AppContainer.js
class AppContainer extends Component {
  render() {
    return (
      <div>
        <NavigationContainer />
        <SnackbarListContainer /> // Display messages when dispatched and re-rendered
        {this.props.children}
      </div>
    )  
  }
}
```

**Comment by mjrussell** [comment]
@ernie-eunsang good idea for a better UX, I think that there are a couple of possible solutions and it depends on if you are using a react router with redux integration. I think the simplest thing you can do is dispatch an extra redux action in the `redirectAction` config parameter. It depends slightly on if you are using a redux + routing middleware integration or if it is vanilla react router. Both require the `redux-thunk middleware` to chain the calls. 


### Using `react-router-redux` or `redux-router` and dispatching an extra redux action in the wrapper
```js
import { replace } from 'react-router-redux'; // Or your redux-router equivalent
import addNotification from './notificationActions';

// Admin Authorization, redirects non-admins to /app
const UserIsAdmin = UserAuthWrapper({
  failureRedirectPath: '/app',
  predicate: user => user.isAdmin,
  redirectAction: (newLoc) => (dispatch) => {
     dispatch(replace(newLoc));
     dispatch(addNotification({ message: 'Sorry, you are not an administrator' }));
  },
  ...
})
```

### Using vanilla React Router with history singleton and extra redux action
```js
import { replace } from 'react-router-redux';
import { browserHistory } from 'react-router';
import addNotification from './notificationActions';

// Admin Authorization, redirects non-admins to /app
const UserIsAdmin = UserAuthWrapper({
  failureRedirectPath: '/app',
  predicate: user => user.isAdmin,
  redirectAction: (newLoc) => (dispatch) => {
     browserHistory.replace(newLoc);
     dispatch(addNotification({ message: 'Sorry, you are not an administrator' }));
  },
  ...
})
```

**Comment by ernie-eunsang** [comment]
That's simple and elegant! 😸  Thank you for detailed explanation.
It'd be nice to add those examples in README to show more advanced usage of `redirectAction`.

**Comment by mjrussell** [comment]
Glad that worked for you 😄. Will do!
