### ISSUE TITLE
Generic action on auth failure instead of redirect

### ISSUE THREAD

**Issue by rewop** [mjrussell/redux-auth-wrapper#66]
I would like to use `redux-auth-wrapper` to optionally render a component (or part of a page) if there is not enough authorisation to view part of the interface. 

The use case is, consider you have a page (for example a blog post), that displays a resource. Depending if the current user owns the resource, I would like to display a set of command (for example Edit post, Delete post). 

I would create an AuthWrapper component that renders the commands only if the user has enough permissions.

For example, given the following component
```jsx
const Commands = (onEdit, onDelete) => {
    <div>
          <button onClick={onEdit}>Edit</button>
          <button onClick={onDelete}>Delete</button>
    </div>
});
```

I would render the `Commands` component with the AuthWrapper:
```jsx
const ProtectedCommands = AuthCanEdit(Commands);

// ...

render() {
    return <ProtectedCommands ... />;
}
```

The `AuthCanEdit` wrapper is configured to look at the store and check if the user as permission to view the wrapped component.

Such use case could be the motivation to abstract the api so that the action on fail is not only a redirect, but could be stopping a component to render, or conditionally show components.

Is there anything planned to support it? If there is enough interest, we could discuss an api for it.

**Comment by rewop** [comment]
I just noticed that there is a PR open for something similar https://github.com/mjrussell/redux-auth-wrapper/pull/61.

I only searched in the issue if something similar was discussed.

**Comment by mjrussell** [comment]
@rewop Yup, we are definitely considering trying to get something just like this in #61. If you have any feedback on the API design for that I would definitely appreciate it.

**Comment by mjrussell** [comment]
You could probably "cheat" right now by making the `authenticatingSelector` be the opposite check of the `authSelector` and using the `LoadingComponent` as your "failure" component. But I want to add something soon that is more flexible.

**Comment by mjrussell** [comment]
@rewop I just pushed `0.8.0` with support for `FailureComponent`. I think that should work for you! I added a [section to the README](https://github.com/mjrussell/redux-auth-wrapper#hiding-and-alternate-components) on how to use it.

Thanks for feedback in the PR!
