### ISSUE TITLE
Example failing

### ISSUE THREAD

**Issue by blitzd** [mjrussell/redux-auth-wrapper#67]
The example [here](https://github.com/mjrussell/react-redux-jwt-auth-example) is failing with the error:

```Uncaught Error: imports[1] for react-transform-catch-errors does not look like a React component.```

**Comment by mjrussell** [comment]
Good catch, looks like this - https://github.com/joshgeller/react-redux-jwt-auth-example/issues/29. I'll pin the dependency

**Comment by mjrussell** [comment]
Resolved in https://github.com/mjrussell/react-redux-jwt-auth-example/commit/d4446bf25ab7cff8186ba5ef6f2d0573498107b4 and https://github.com/mjrussell/react-redux-jwt-auth-example/commit/35eb1ed3e58bd8ab7f9767438f4773a0c8020cbc

Thanks!
