### ISSUE TITLE
Passing Props Warning React 15.3.0

### ISSUE THREAD

**Issue by B-Stewart** [mjrussell/redux-auth-wrapper#69]
We have upgraded to React 15.3.0 from 15.1.0 and are now receiving this warning while using your wrapper.

```
Warning: Unknown props `history`, `location`, `params`, `route`, `routeParams`, `routes` on <span> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in span (created by RequireAuthentication(Connect(UserEvaluations)))
    in RequireAuthentication(Connect(UserEvaluations)) (created by Connect(RequireAuthentication(Connect(UserEvaluations))))
    in Connect(RequireAuthentication(Connect(UserEvaluations))) (created by RouterContext)
    in div (created by Gateway)
    in Gateway (created by Connect(Gateway))
    in Connect(Gateway) (created by RouterContext)
    in RouterContext (created by Router)
    in ScrollBehaviorContainer (created by Router)
    in Router
    in Provider
```

It references [this](https://facebook.github.io/react/warnings/unknown-prop.html) documentation which deals with passing props. My guess is the way that you are passing the props to the loading component (in this case the default <span/> is making React upset.

Here are what my auth wrappers look like in case that is helpful or the issue is actually on my side

```
mport { UserAuthWrapper } from 'redux-auth-wrapper'

export const RequireAuthentication = UserAuthWrapper({
  authSelector: state => state.auth,
  predicate: auth => auth.isAuthenticated,
  authenticatingSelector: state => state.auth.fetching,
  wrapperDisplayName: 'RequireAuthentication'
})

export const IgnoreIfAuthenticated = UserAuthWrapper({
  authSelector: state => state.auth,
  failureRedirectPath: '/',
  predicate: auth => !auth.isAuthenticated,
  authenticatingSelector: state => state.auth.fetching,
  wrapperDisplayName: 'IgnoreIfAuthenticated',
  allowRedirectBack: false
})
```

**Comment by mjrussell** [comment]
Yeah you are totally correct on this, it is actually fixed by #63 and in master. I was initially waiting on a few more things for a release version but Im just going to get it out today. I'll close this when I do.

**Comment by mjrussell** [comment]
Release 0.7.0 just now. Should be fixed. 

Feel free to re-open if it isn't resolved but there is a test for it so Im fairly confident.

**Comment by larsw** [comment]
Hi,

 I'm experiencing the same problem (currently on version 0.8.0) when I wrap an NavDropdown control from react-bootstrap (which renders an anchor element):

```
Warning: Unknown props `authData, `failureRedirectPath` on <a> tag.  ...
```

**Comment by mjrussell** [comment]
@larsw I do want to add a parameter to disable passing the authData down, see #28. We shouldn't be passing down the failureRedirectPath though since thats probably useless to the decorated component...that seems like a bug. I would think the only thing that should be passed is authData and then control that with a flag.

#28 isn't hard to implement, I've just been pretty busy lately. I can try to get to it soon, but probably not for another week. In the meantime, you should be able to use a function component to wrap the control and drop the props. Something like:

```js
const myWrapper = UserAuthWraper({
...
})

// Instead of myWrapper(NavDropdown)
myWrapper(() => <NavDropdown />)
```
