### ISSUE TITLE
Example with Modals and not redirect

### ISSUE THREAD

**Issue by ansumanshah** [mjrussell/redux-auth-wrapper#70]
Can we use login modals rather then a complete redirect?

**Comment by mjrussell** [comment]
Currently I think it is possible, but a little painful. Implementing #61 would enable this pretty easily (render the modal as the `FailureComponent`). 

Until then it depends a bit on how you are displaying Modals in your app. If you can display them via dispatching redux action then you could co-opt the `redirectAction` parameter.

```js
function showLoginModal() { 
  return {
    type: 'SHOW_LOGIN_MODAL',
  };
}

const UserIsAuthenticated = UserAuthWrapper({
  authSelector: state => state.user,
  redirectAction: showLoginModal,
  wrapperDisplayName: 'UserIsAuthenticated'
})
```

This wont trigger a redirect and instead dispatch `showLoginModal` if the user is not authenticated.

**Comment by mjrussell** [comment]
The previous comment describes how to display modals if you dispatch an action to show your modal. Alternatively, if you need to render a component which displays your modal, you can use the `FailureComponent` added in `0.8.0`.

Something like:
```js
const UserIsAuthenticated = UserAuthWrapper({
  authSelector: state => state.user,
  wrapperDisplayName: 'UserIsAuthenticated',
  FailureComponent: LoginModal
})
```

Im going to close this issue but if you have further questions feel free to reopen
