### ISSUE TITLE
production support?

### ISSUE THREAD

**Issue by cch5ng** [mjrussell/redux-auth-wrapper#72]
hi @mjrussell I'm currently looking for an auth package and was wondering are you using redux-auth-wrapper for any production applications or know of any companies using redux-auth-wrapper in production so far? are you sponsored to work on the project or is it a side project? thanks!

**Comment by andrewmclagan** [comment]
We are using this project in production.

**Comment by mjrussell** [comment]
Hi @cch5ng, I am also using this library in a production app for my company (SimSpace). I am not sponsored to work on this project although my company gives me the ability to work on this project during my free time.

**Comment by cch5ng** [comment]
thanks @andrewmclagan and @mjrussell . good to know!
