### ISSUE TITLE
Could you add flag to stop redirect after successfully authorised ? 

### ISSUE THREAD

**Issue by kamalpatel125** [mjrussell/redux-auth-wrapper#74]
Hi,
First of all thanks for doing great work. Just wondering, if you could allow to stopRediect flag then it would be really helpful if i need to authorised individual component based on specific permission.

For e.g. I have two components One, Two and rendering on Main component. 
Component one requires some authorisation based on permission and component two doesn't need that. So if Component one failed the authorisation, don't want to redirect because still want to render  component Two. Hope this make sense. Currently, I am doing like below;
 UserAuthWrapper({
        authSelector: state => state.auth,
        predicate: predicateFn,
        wrapperDisplayName: 'UserIsAuthorised',
        stopRedirect: true
    }
and in the library, I am checking for this flag before redirecting. 

Thanks again for great work !

Regards,

Kamal Patel.

**Comment by mjrussell** [comment]
@kamalpatel125 I think that your use case would be handled by #66 and the pr in #61. 

With this PR you would specify a FailureComponent of `null` which would hide the component if it failed to match the predicate, instead of causing a redirect to occur.

**Comment by kamalpatel125** [comment]
Hi,

Could not found any flag "failureComponent" in your source code to pass as null so it won't redirect. Or I am missing something here.

Thanks 

Kamal.

**Comment by mjrussell** [comment]
Yeah the issue and PR I linked are still open. This is a new feature we are adding to redux-auth-wrapper right now. It should be added fairly soon.

**Comment by mjrussell** [comment]
@kamalpatel125 The `FailureComponent` has been merged in and the documentation updated. It is now available in `0.8.0`. 

Please check out the [section in the README](https://github.com/mjrussell/redux-auth-wrapper#hiding-and-alternate-components) for how to use it or the basic example.

Feel free to re-open this issue if something is not clear.
