### ISSUE TITLE
Use with immutablejs and reselect

### ISSUE THREAD

**Issue by tobyl** [mjrussell/redux-auth-wrapper#78]
Hi there

I'm importing `UserAuthWrapper` into a container which will be the parent for all protected routes (I'm using dynamic routes so I can't use with routing).

My problem is that I'm using immutablejs and reselect, and I'm having trouble getting the `authSelector` and `predicate` parts right.

I've followed the docs and tried many different solutions, so any feedback greatly appreciated!

```
import React from 'react';
import { connect } from 'react-redux';
import { createStructuredSelector } from 'reselect';
import selectAccount, { loggedInSelect } from './selectors';
import { UserAuthWrapper } from 'redux-auth-wrapper';
import { routerActions } from 'react-router-redux';

const userIsAuthenticated = UserAuthWrapper({
  authSelector: state => state.home,
  predicate: home => home.get('loggedIn'),
  redirectAction: routerActions.replace,
  wrapperDisplayName: 'UserIsAuthenticated',
  failureRedirectPath: '/',
});

export class Account extends React.Component {
  render() {
    return (
      <div>
        <h2>Secret area</h2>
        logged in: {this.props.loggedIn ? 'no' : 'yes'}
      </div>
    );
  }
}

const mapStateToProps = createStructuredSelector({
  home: loggedInSelect(),
  account: selectAccount(),
});

function mapDispatchToProps(dispatch) {
  return {
    dispatch,
  };
}

export default connect(mapStateToProps, mapDispatchToProps)(userIsAuthenticated(Account));
```

**Comment by mjrussell** [comment]
@tobyl nothing jumps out to me immediately as being wrong with your setup, could you explain a little bit more what is not working for you? I cant think of a reason why immutableJS or reselect would interfere with the library, besides needing to change the configuration of the predicate (and maybe authSelector if you entire state object is an immutable object).

Does it not redirect? Are there failed proptype warnings?

One useful debugging strategy is to console.log in your `predicate` function to see what is being passed into it.

**Comment by tobyl** [comment]
Apologies - the error I see with the above setup is:

`Dynamic page loading failed TypeError: Cannot read property 'loggedIn' of undefined(…)`

But I have to add/remove the `userIsAuthenticated(Account)` block to test each time - is there a way I can test to see what authSelector is trying to use from state?

Many thanks for the response.

**Comment by mjrussell** [comment]
> But I have to add/remove the userIsAuthenticated(Account) block to test each time - is there a way I can test to see what authSelector is trying to use from state?

Im not sure I understand what you mean here, probably its crashing the page (React doesn't have error boundaries yet) but you should to be able to just force a reload by refreshing the page.

As for your error, it sounds like the authSelector is returning undefined.

Its not clear to me how you have your reducers setup and in your example the use of `maptStateToProps` and `mapDispatchToProps`.

It seems like your `authSelector` should use your `loggedInSelector`. Additionally, you only need to have that wrapper `connect` if you need to pass data through the authWrapper to the wrapped component. You should be able to write it as 

`connect(mapStateToProps, mapDispatchToProps)(userIsAuthenticated(Account));`
or
`userIsAuthenticated(connect(mapStateToProps, mapDispatchToProps)(Account));`
without any change in behavior. 

So maybe your code looks more like:

```js
import React from 'react';
import { loggedInSelect } from './selectors';
import { UserAuthWrapper } from 'redux-auth-wrapper';
import { routerActions } from 'react-router-redux';

const userIsAuthenticated = UserAuthWrapper({
  authSelector: state => loggedInSelect(),
  predicate: home => home.get('loggedIn'),
  redirectAction: routerActions.replace,
  wrapperDisplayName: 'UserIsAuthenticated',
  failureRedirectPath: '/',
});

export class Account extends React.Component {
  render() {
    return (
      <div>
        <h2>Secret area</h2>
        logged in: {this.props.authData.get('loggedIn') ? 'no' : 'yes'}
      </div>
    );
  }
}

export default userIsAuthenticated(Account);
```

**Comment by tobyl** [comment]
That's super-helpful - thank you so much. I'll fiddle with this and report back with findings. Thanks again for the quick response!

**Comment by MrRoyce** [comment]
I am using the wrapper with immutable.js.  I think the thing to do is make sure the authSelector matches the attribute name in your (combined) reducers.  This is how my combined reducer looks

```javascript
const rootReducer = combineReducers({
 ...
  userData : User
});
```

And this is how the wrapper looks
```javascript
const AdminAuth = UserAuthWrapper({
  authSelector : state => state.userData, // this has to be the same name as in the reducer
  predicate    : (userData) => {
    // use immutable js functions to determine authorization
  },
...
});
```

Actually I use 'selectors'  in the reducer so that other components dont have to know the state structure.  I'm not sure how to use those selectors with the wrapper, so I can skip the immutable js 'get' functions

**Comment by mjrussell** [comment]
> I think the thing to do is make sure the authSelector matches the attribute name in your (combined) reducers. 

Yeah that is definitely the critical first step. The trick is that some setups using ImmutableJS dont use combineReducers (because that uses plain objects under the hood) like you do so it can be confusing if you don't understand how the reducers are put together.  

>  I'm not sure how to use those selectors with the wrapper, so I can skip the immutable js 'get' functions

@MrRoyce you should be able to use your selectors in the auth wrapper the same way you do when using `connect` 

In an ideal world, the authSelector should be responsible for pulling the user information out of the store and the predicate for any checks that have to be performed on that data (like how to check for being an administrator).

**Comment by mjrussell** [comment]
@tobyl any update on this? Wondering I can close this issue now

**Comment by mjrussell** [comment]
Also check out this nice example of using ImmutableJS with redux-auth-wrapper  - https://github.com/mjrussell/redux-auth-wrapper/issues/83#issuecomment-249032128
