### ISSUE TITLE
Hide link error : Cannot read property 'pathname' of undefined.

### ISSUE THREAD

**Issue by RomaniaHate** [mjrussell/redux-auth-wrapper#82]
Hi I'm having a trouble trying to hide a link for an unauthorized user.
I received this error : **Uncaught TypeError: Cannot read property 'pathname' of undefined.**
and this :**Warning: Failed prop type: Required prop `location` was not specified in `isLinkVisible (Component)`.**
If I add `allowRedirectBack: false,` is redirecting me to '/login'

Auth Wrapper:
```
export const isLinkVisible = UserAuthWrapper({
    authSelector: state => state.user,
    wrapperDisplayName: 'isLinkVisible ',
    predicate: user => false,
    FailureComponent: null
});
```
Component
```
interface SideBarProps {
    drawerOpened: boolean;
    closeDrawer: () => void;
}

class SideBar extends React.Component<SideBarProps, any> {
    constructor(props: SideBarProps) {
        super(props);
    }

    render(): JSX.Element {
        let IsLinkVisible: any = isLinkVisible(()=><Link to='/'>Is visible</Link>);
        return (
            <Drawer
                open={this.props.drawerOpened}
                docked={false}
                onRequestChange={this.props.closeDrawer}
                disableSwipeToOpen={false}
                width={280}>
                <IsLinkVisible/>
            </Drawer>
        )
    }
}

export default connect(
    (state: any, ownProps) => (Object.assign({}, state, {
        drawerOpened: state.app.drawerOpened,
    })),
    {
        closeDrawer: () => toggleDrawer(TOGGLE_DRAWER, false),
    }
)(SideBar);
```

**Comment by mjrussell** [comment]
Hmm it looks like its not picking up the FailureComponent being set to nullify and its trying to pull the location out of the router since it thinks it should redirect. @RomaniaHate what does your package json look like for redux-auth-wrapper, could you be on a version older than 0.8?

**Comment by RomaniaHate** [comment]
@mjrussell I have installed 
 "redux-auth-wrapper": "^0.5.2"

**Comment by mjrussell** [comment]
@RomaniaHate can you go to `"redux-auth-wrapper": "^0.8.0"` and re-run `npm install`? You are using a new feature in 0.8 so it'd be best to pin above that

**Comment by RomaniaHate** [comment]
@mjrussell Looks like it solved my problem, thanks.
