### ISSUE TITLE
What happens during the reload ?

### ISSUE THREAD

**Issue by Lakshman-LD** [mjrussell/redux-auth-wrapper#86]
- I understand how redux-auth-wrapper works. So it basically checks whether the give user is authenticated from the state object. 
- **In case of a reload, All your state objects are gone.** So, will it redirect the user to home-page and ask them to log-ion again? (correct me If I am wrong)
- But in case of authentication in servers, the oauth something like passport(npm pkg) in nodeJS saves the session, so when you reload, it gives you from the session and you dont need to login again. (Correct me If I am wrong)
- So how do we approach the above step in client?

**Comment by mjrussell** [comment]
@Lakshman-LD good question. You are correct that the defaults for redux-auth-wrapper would redirect them to the home page and ask for their login credentials on every reload. This is obviously not ideal when auth resides on the server. 

This was the reasoning behind adding the `isAuthenticating` selector and `LoadingComponent` config options to redux-auth-wrapper. You can use them in tandem to display a Spinner or some other loading indication while your application loads. 

The basic steps are the following:
1. Initialize a boolean flag in your reducer to be true for the user is loading
2. Return this boolean from the `isAuthenticating` selector passed to `UserAuthWrapper`
3. Add a `LoadingComponent` which displays some loading indicator
4. When the app loads, either in your root component's `componentDidMount` (or in a saga if using redux-saga) on load, you can dispatch a fetch for the user information. If this returns data, set the user reducer to that data. Also set the loading indicator flag in the reducer to false.

The auth wrapper will delay redirecting the user to Login until `isAuthenticating` returns false and the predicate applied to the `authSelector` returns false.

Let me know if anything is unclear about this approach.

**Comment by mjrussell** [comment]
Going to close this, hope it was helpful

**Comment by codematcha** [comment]
I am quite new to this and stuck on step 4. As the server doesn't keep the state how can I get the user information from the server when the page has refreshed? In your example code, App is a function instead of a react component, so I am also unsure on where to place componentDidMount? I am using react boilerplate and redux-auth-wrapper. Thanks a lot.
