### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by heyxiaoling** [mjrussell/redux-auth-wrapper#87]
ERROR in C:/Users/**_/Desktop/mygithub/redux-auth-wrapper/src/index.js
Module build failed: ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "C:\Users\**_\Desktop\mygithub\redux-auth-wrapper\.babelrc" at 0, attempted to resolve relative to "C:\Users\**_\Desktop\mygithub\redux-auth-wrapper"
    at C:\Users\**_\Desktop\mygithub\redux-auth-wrapper\examples\localStorage\node_modules\babel-core\lib\transformation\file\options\option-manager.js:172:17

**Comment by mjrussell** [comment]
@heyxiaoling did you `npm install` from the project directory before running `npm install` in the example folder?

**Comment by tauren** [comment]
I ran into the same problem. Doing an `npm install` in both the project directory and in the example folder solved the problem. This issue should be able to be closed.

**Comment by mjrussell** [comment]
Thanks @tauren. Since the example README says to run `npm install` in the project directory first Im going to close this.
