### ISSUE TITLE
UserAuthWrapper not rendering in Unit Test

### ISSUE THREAD

**Issue by Blackclaws** [mjrussell/redux-auth-wrapper#88]
So I've been trying to build Unit Tests for my configured UserAuthWrappers as is required by our coding guidelines. So far I've not been able to succeed in getting them to render or even run the authSelector.

I'm using Karma + Chai + Chai-Enzyme and using Enzymes mount function to mount a small snippet:

      <Provider store={store}>
        <div>
        {userIsAuthenticated(testComponent)}
        </div>
      </Provider>

Where store is created right before using the same function used in the application itself (where UserAuthWrapper works as expected :) )

I've been trying to debug this issue for a while now. So far I've come up empty handed. I only know that inside the unit test mapStateToDispatch is not even called and neither is the authSelector or componentWillMount. 

I'm wondering whether this is actually a connect related issue rather than a redux-auth-wrapper one.

**Comment by Blackclaws** [comment]
Interestingly enough @connect does not seem to run...

**Comment by Blackclaws** [comment]
I've now added console logs to every single function of UserAuthWrapper. On the normal page all the function fire normally:

Getting state for UserIsAuthenticated
index.js:105 Mapping dispatch to props
index.js:156 Component will mount
index.js:70 Predicate is
index.js:71 false
index.js:186 creatingRedirect

On the Karma Debug Page for the Unit Test I am left with none of these. Just that the wrapComponent function is called for creating the UserIsAuthenticated component.

**Comment by mjrussell** [comment]
@Blackclaws `userIsAuthenticated(testComponent)` returns a component so you need to first create a react element with it before you can render it. You should be doing something like:
```js
const MyWrappedComponent = userIsAuthenticated(testComponent)

  <Provider store={store}>
    <div>
      <MyWrappedComponent />
    </div>
  </Provider>
```

**Comment by Blackclaws** [comment]
That did fix the problem. I was under the impression I could use react components with the {} syntax as well since it works for pure JSX but I guess that is just inserted and parsed afterwards.

Thanks a lot. The test is now working.

**Comment by mjrussell** [comment]
Theres a few differences between React Components, Elements, and Instances. Dan Abramov has a great post about them and is worth a read:

https://medium.com/@dan_abramov/react-components-elements-and-instances-90800811f8ca#.s2426inua
