### ISSUE TITLE
FailureComponent returning a function, not running 

### ISSUE THREAD

**Issue by srisonti** [mjrussell/redux-auth-wrapper#91]
I have a couple of questions regarding `FailureComponent` and the set up for showing partial data. I'm currently running `^0.8.0` of `redux-auth-wrapper`.

The first issue I'm having is related to hiding a button on the page. 

```
// the authWrapper
const VisibleOnlyIfOrgAdminOrManager = UserAuthWrapper({
  authSelector: function(state) { console.log('is this running?', state, state.get('app').toJS()); return state.get('app'); },
  wrapperDisplayName: 'VisibleOnlyIfOrgAdminOrManager',
  predicate: function(auth) { console.log('is this running as well?', auth, auth.get('currentUser').toJS()); return true; },
  FailureComponent: null,
});

// the authWrapper being used inside of the render() function
render() {
  const teamsLoading = this.props.teamsLoading;
  const teamsError = this.props.teamsError;
  const openCreateNewTeamModal = this.props.openCreateNewTeamModal;

  ...

  const newTeamButton = VisibleOnlyIfOrgAdminOrManager(() => {
    return (
      <button onClick={this.props.openCreateNewTeamModal} className={`${teamsStyles.teamsHeaderOption} ${buttonStyles.button} ${buttonStyles.primary} ${buttonStyles.outline}`}>
        Create New Team
      </button>
    );
  });

  console.log('what is this the newTeamButton?', newTeamButton);

  ...
}
```

the output for the `console.log` statement is returning a function as follows:

```
what is the newTeamButton? Connect(props, context) {
        _classCallCheck(this, Connect);

        var _this = _possibleConstructorReturn(this, _Component.call(this, props, context));

        _this.version = versio…
```

But none of the `console` statements from inside the authWrapper itself are running (the `authSelector` and `predicate`). I'm following the examples that other people have, and I've browsed the other issues, but I can't see anything that I'm doing differently here. Is there something obvious I'm overlooking?

The second question I have is related to the best practices for passing on role-restricted data to components. I have a component that takes data that is dependent on the role. 

```
// inside my render() function for one of my containers
render() {
  const roles = UserCheck.getRolesList(this.props.currentUser.get('organizationMembership'));

...

  <UserList
    ...
    users={this.props.team.get('users')}
    userRoleOptions={roles}
    ...
  />
}
```

The `roles` are used inside my `UserList` component in a couple of different places. However, the roles that are sent in should be limited based on the permission level of the `currentUser`. I have my own `UserCheck` object that checks permissions based on the user properties, but is there any way to move it to an authWrapper? If there's a better way to structure all of this so that I can use `redux-auth-wrapper` across the board, that would be ideal.

Thanks again for making such an awesome package :)

**Comment by mjrussell** [comment]
Lets start with the first issue.

The return value of applying the HOC is a Component. It is not an instance of component (See Dan Abromov's great post on this if want to learn more about the differences [here](https://medium.com/@dan_abramov/react-components-elements-and-instances-90800811f8ca#.q7n7ksmyx)). So you need to create an instance from the component. This is typically done with JSX like this:
```js
  const NewTeamButton = VisibleOnlyIfOrgAdminOrManager(() => {
    return (
      <button onClick={this.props.openCreateNewTeamModal} className={`${teamsStyles.teamsHeaderOption} ${buttonStyles.button} ${buttonStyles.primary} ${buttonStyles.outline}`}>
        Create New Team
      </button>
    );
  });

 <NewTeamButton />
```
This is why the selectors never run because the component is never instantiated.

Additionally, I would discourage applying the HOC (in your case `VisibleOnlyIfOrgAdminOrManager`) inside the render method. Applying an HOC returns a new component and React can make optimizations if it knows it is the same component class but with potentially different props. In your case, you are making a new component class each time inside your render. Instead, I'd recommend you define that wrapped button above as so:
```js
  const NewTeamButton = VisibleOnlyIfOrgAdminOrManager((props) => {
    return (
      <button onClick={props.openCreateNewTeamModal} className={`${teamsStyles.teamsHeaderOption} ${buttonStyles.button} ${buttonStyles.primary} ${buttonStyles.outline}`}>
        Create New Team
      </button>
    );
  });

  ...
  render() {
   ...
   <NewTeamButton onClick={this.props.openCreateNewTeamModal} />
   ...
  }
```

**Comment by mjrussell** [comment]
Reading over your second question, Im not exactly sure what kind of solution you are looking for. Are there actions/data inside the UserList that you want to limit based on a role? Could you define more wrappers and apply them inside the UserList to filter these things based on the roles?

Also keep in mind that you can define your own HOC similar to redux-auth-wrapper but that more naturally fits your data. The code for this library is pretty short and much of it focuses on redirection logic. You could create an HOC that is focused on providing specific functionality to your user list

**Comment by srisonti** [comment]
My UserList component has the ability to edit a user that is limited only to Admins and Managers. If the user has the appropriate privileges, then an edit icon shows up. Also, a Manager is not allowed to promote anyone to an Admin (for obvious security issues). 

I basically just wanted to see if I could use redux-auth-wrapper for everything, but it makes sense to make my own for my own needs. Thanks for the input.

Regarding the first question - do you have any idea what I might be doing incorrectly? I've been tinkering with things and I haven't had much luck getting it to work.

**Comment by mjrussell** [comment]
> My UserList component has the ability to edit a user that is limited only to Admins and Managers. If the user has the appropriate privileges, then an edit icon shows up. Also, a Manager is not allowed to promote anyone to an Admin (for obvious security issues).

Seems like you could wrap that edit button as well in an auth-wrapper. The `authSelector` can return data based on the props (second argument) and you can write a custom predicate if you need to (see the docs for this). 

> Regarding the first question - do you have any idea what I might be doing incorrectly? I've been tinkering with things and I haven't had much luck getting it to work.

Did you read my first comment? Did you try the instructions there?
https://github.com/mjrussell/redux-auth-wrapper/issues/91#issuecomment-260067471

**Comment by srisonti** [comment]
@mjrussell ah, I was on sketchy internet when I posted that earlier so I didn't see the first comment for some reason. Yes, I tried your fix and it worked perfectly. Thanks for linking to Dan Abromov's post - it's a good clarification for me to know about :)

Everything else is working correctly for me, so feel free to close this issue. Thanks again for your help! I really appreciate it.

**Comment by mjrussell** [comment]
@srisonti no problem, I was just a little confused for a minute. Glad it worked!
