### ISSUE TITLE
How to define a unauthenticated wrapper?

### ISSUE THREAD

**Issue by mrold** [mjrussell/redux-auth-wrapper#95]
For example, if user has logged in, it is not allowed to visit the "Login Page", and it will be redirected to the "Home Page".
Could you please give me some suggestions?

**Comment by mjrussell** [comment]
Hi @mrold, take a look at https://github.com/mjrussell/redux-auth-wrapper/issues/2#issuecomment-237728665. Also the loading example has an example of this https://github.com/mjrussell/redux-auth-wrapper/blob/master/examples/loading/app.js#L55-L63

**Comment by mrold** [comment]
Great! Thank you very much! @mjrussell
