### ISSUE TITLE
Best way to disable all authentication/authorization checks

### ISSUE THREAD

**Issue by gonzalad** [mjrussell/redux-auth-wrapper#97]
Hello,

I would like to disable all authentication/authorization checks in a simple way.
This will be used for dev-purposes only.

I can customize the predicate in each of my UserAuthWrapper like this, but it really feels ugly :

```
const UserIsAuthenticated = UserAuthWrapper({
	authSelector: state => state.oidc.user,
	authenticatingSelector: state => state.oidc.isLoadingUser,
    predicate: user => Configuration.security.disabled || !isEmpty(user),
	redirectAction: routerActions.replace,
	wrapperDisplayName: 'UserIsAuthenticated',
});
```

Is there a better way ?

Thanks,

**Comment by mjrussell** [comment]
I think using the predicate is the right idea if you want to apply the AuthWrapper to your component. Another option could be to not even apply the auth wrapper in "dev mode". Something like:
```js
let UserIsAuthenticated;

if (_DEV_) {
 UserIsAuthenticated = x => x; // This is the identity function, doesn't change the passed in component
 // another option with lodash is _.identity
} else {
 UserIsAuthenticated = UserAuthWrapper({
	authSelector: state => state.oidc.user,
	authenticatingSelector: state => state.oidc.isLoadingUser,
	redirectAction: routerActions.replace,
	wrapperDisplayName: 'UserIsAuthenticated',
  });

export UserIsAuthenticated
```

You could use webpack's define plugin and then webpack's uglify JS will remove dead code and it wont ship in production builds.

**Comment by gonzalad** [comment]
Good idea, I'll go with yoursecond option !
Thanks foryour insight @mjrussell
