### ISSUE TITLE
How to redirect from login/signup page when user authorized?

### ISSUE THREAD

**Issue by ideal-life-generator** [mjrussell/redux-auth-wrapper#98]
You provide functional for pages what required authentication. But what if I already authorized, and I want go to '/login' or '/signup' pages? This plugin can redirect me from '/login', '/signup' pages when I already authorized?

**Comment by mjrussell** [comment]
See https://github.com/mjrussell/redux-auth-wrapper/issues/95 for the authorized redirect. 

> Also it have a bug:
When I in page and is needed redirect path, and I reload it plugin add redirect url param all times so url can be like /login?reditect=/&reditect=/&reditect=/ etc. I think you know.


Sorry, I don't understand what you are describing. The redirect url param should only be added once. It may be dependent on what version of history you are using and if you are using hash history vs browser history

**Comment by mjrussell** [comment]
@ideal-life-generator looks like you changed the original question. For creating an "unauthenticated wrapper" check out https://github.com/mjrussell/redux-auth-wrapper/issues/95

**Comment by ideal-life-generator** [comment]
@mjrussell Thank you for feedback, I will read.
